### ISSUE TITLE
Caffee Grande and hot water missing

### ISSUE THREAD

**Issue by Phoenix-DH** [thoukydides/homebridge-homeconnect#122] opened 2023-01-23 19:12 UTC
Hey,

thanks for this great plugin.
I just bought a Siemens EQ 700 and started to use it.
I figured out that my favourite, Caffee Grande and hot water are missing.

Can you please add it?

Thank you s lot.

**Comment by thoukydides** [comment] 2023-01-24 03:50
> I figured out that my favourite, Caffee Grande and hot water are missing.
> 
> Can you please add it?

Sorry, no, that is not possible. This plugin does not include any list of known or supported programs. It obtains details of programs supported by a particular appliance from the Home Connect API, and makes them all available. If programs are missing then it is because they are not supported by Home Connect. There is nothing that I can do about that.

The list of Coffee Machine programs supported by Home Connect can be found here: https://api-docs.home-connect.com/programs-and-options?#coffee-machine

You will need to ask the Home Connect team to add any omissions: https://developer.home-connect.com/support/contact

This is a duplicate of #44.

**Closed** 2023-01-24 03:51 UTC

**Comment by Phoenix-DH** [comment] 2023-01-24 04:58
Hey, ok, understood.
Thank you for the fast reply.

**Comment by thoukydides** [comment] 2023-02-07 16:44
The Home Connect API now supports `ConsumerProducts.CoffeeMaker.Program.Beverage.CaffeGrande` (https://developer.home-connect.com/changelog). If that is supported by your appliance via the API then it should work with this plugin. You will need to restart Homebridge to trigger a re-read of available programs.
