### ISSUE TITLE
Config fails to load on Node.js v20.9.0 (latest available on Synology)

### ISSUE THREAD

**Issue by connor-g** [thoukydides/homebridge-homeconnect#304] opened 2024-10-07 14:54 UTC
### Description of Issue

I'm running the latest HomeBridge and HomeConnect on a Synology, and as far as I can tell the latest version of Node.js offered on Synology is v20.9.0.

### Expected Behaviour

Plugin should load successfully on Node.js v20.9.0

### Steps to Reproduce

When starting up, plugin emits this output:

```
[10/7/2024, 9:48:34 AM] The plugin "homebridge-homeconnect" requires Node.js version of ^22.8.0 || ^20.17.0 || ^18.20.4 which does not satisfy the current Node.js version of v20.9.0. You may need to upgrade your installation of Node.js - see https://homebridge.io/w/JTKEF
[10/7/2024, 9:48:34 AM] ====================
[10/7/2024, 9:48:34 AM] ERROR LOADING PLUGIN homebridge-homeconnect:
[10/7/2024, 9:48:34 AM] SyntaxError: Unexpected token 'with'
    at ModuleLoader.moduleStrategy (node:internal/modules/esm/translators:118:18)
    at callTranslator (node:internal/modules/esm/loader:273:14)
    at ModuleLoader.moduleProvider (node:internal/modules/esm/loader:278:30)
[10/7/2024, 9:48:34 AM] ====================
```

### Plugin Version

1.0.4

### Environment

- OS: Synology DMS 7.2.1
- Node: 20.9.0
- Homebridge: 1.8.4

### Diagnostic Checks

- [X] Home Connect app is able to control the appliance with Wi-Fi disabled.
- [X] Home Connect app shows three green lines in the Network section of the appliance Settings.
- [X] Unofficial [Home Connect Server Status](https://homeconnect.thouky.co.uk) shows servers up and no recent errors.
- [X] Searched for [previously reported issues](https://github.com/thoukydides/homebridge-homeconnect/issues?q=is%3Aissue) and no similar ones found.
- [X] Checked the [Home Connect API errors](https://api-docs.home-connect.com/general?#api-errors) and [authorisation errors](https://api-docs.home-connect.com/authorization?#authorization-errors) documentation.

### Log File

```shell
[10/7/2024, 9:48:34 AM] The plugin "homebridge-homeconnect" requires Node.js version of ^22.8.0 || ^20.17.0 || ^18.20.4 which does not satisfy the current Node.js version of v20.9.0. You may need to upgrade your installation of Node.js - see https://homebridge.io/w/JTKEF
[10/7/2024, 9:48:34 AM] ====================
[10/7/2024, 9:48:34 AM] ERROR LOADING PLUGIN homebridge-homeconnect:
[10/7/2024, 9:48:34 AM] SyntaxError: Unexpected token 'with'
    at ModuleLoader.moduleStrategy (node:internal/modules/esm/translators:118:18)
    at callTranslator (node:internal/modules/esm/loader:273:14)
    at ModuleLoader.moduleProvider (node:internal/modules/esm/loader:278:30)
[10/7/2024, 9:48:34 AM] ====================
```

### Configuration

```json
{
    "platform": "HomeConnect",
    "name": "HomeConnect",
    "clientid": "redacted",
    "simulator": false,
    "language": {
        "api": "en-US"
    },
    "THERMADOR-DWHD560CFP-68A40E956B8B": {
        "enabled": false,
        "names": {
            "prefix": {
                "programs": false,
                "other": true
            }
        },
        "features": {
            "Active Program": false,
            "Door": false,
            "Event Buttons": false
        },
        "addprograms": "none",
        "programs": []
    },
    "THERMADOR-T36FT820NS-68A40E8F6603": {
        "enabled": true,
        "names": {
            "prefix": {
                "programs": false,
                "other": true
            }
        },
        "features": {
            "Door": true,
            "Event Buttons": false,
            "Internal Light": false,
            "Freezer Super Mode": false,
            "Fresh Mode": false,
            "Refrigerator Super Mode": false,
            "Vacation Mode": false,
            "Eco Mode": false,
            "Ice Dispenser": false,
            "Sabbath Mode": false,
            "Freezer Door": false,
            "Refrigerator Door": false
        }
    },
    "THERMADOR-PH36GWS-68A40EA35791": {
        "enabled": true,
        "names": {
            "prefix": {
                "programs": false,
                "other": true
            }
        },
        "features": {
            "Event Buttons": false,
            "Functional Light": true
        }
    },
    "THERMADOR-PRG366WH-68A40EA265E3-001": {
        "enabled": false,
        "names": {
            "prefix": {
                "programs": false,
                "other": true
            }
        },
        "features": {
            "Active Program": false,
            "Door": false,
            "Event Buttons": false,
            "Sabbath Mode": false
        },
        "addprograms": "none",
        "programs": []
    },
    "THERMADOR-POM301W-68A40EA40AE3-001": {
        "enabled": false,
        "names": {
            "prefix": {
                "programs": false,
                "other": true
            }
        },
        "features": {
            "Active Program": false,
            "Door": false,
            "Event Buttons": false,
            "Sabbath Mode": false
        },
        "addprograms": "none",
        "programs": []
    }
}
```

**Comment by thoukydides** [comment] 2024-10-07 15:19
This is a duplicate of #300.

A breaking change was made to Node.js, so to work with the latest LTS releases I had to make a change to this plugin that makes it incompatible with earlier versions. The minimum supported Node.js versions should now be: 18.20, 20.10, or 22. However I only test against the latest versions on each LTS branch, which is why the `package.json` specifies higher versions than these.

You will need to stay on v1.0.3 of this plugin until Synology release a sufficiently up-to-date version of Node.js.

**Closed by thoukydides** 2024-10-07 15:19 UTC
Labels: bug

**Comment by connor-g** [comment] 2024-10-07 15:20
Thanks for the quick answer!

**Comment by thoukydides** [comment] 2024-10-08 19:24
[v1.0.5](https://github.com/thoukydides/homebridge-homeconnect/releases/tag/v1.0.5) should restore compatibility with Node.js 20.9.0.
