### ISSUE TITLE
[HomeConnect] Failed to read list of home appliances: TypeError: Home Connect API error: AbortSignal.timeout is not a function

### ISSUE THREAD

**Issue by PNK1974** [thoukydides/homebridge-homeconnect#89] opened 2022-05-30 10:55 UTC
#### Description of Issue
Hello, last days I have this red error message in my log, every time, I started HB:
[HomeConnect] Failed to read list of home appliances: TypeError: Home Connect API error: AbortSignal.timeout is not a function

#### Plugin Version
homebridge-homeconnect v0.24.4

#### Home Connect Appliance(s)
Everything from Siemens

#### Log File
[5/30/2022, 12:43:24 PM] [HomeConnect] Failed to read list of home appliances: TypeError: Home Connect API error: AbortSignal.timeout is not a function

**Comment by thoukydides** [comment] 2022-05-30 11:12
What version of Node.js are you using?

This static method was a added in Node.js v17.3.0 and v16.14.0.
The `package.json` for this plugin specifies a minimum requirement of v16.14.0.

**Comment by thoukydides** [comment] 2022-05-30 11:15
This appears to be a duplicate of #80.

**Comment by thoukydides** [comment] 2022-05-30 12:12
I only run homebridge under Ubuntu, with my own systemd configuration launching `/usr/local/bin/homebridge`. This uses the version of `node` that is on the user's `PATH`. So, just running `node -v` as the same user reports the version being used.

I have never used a Synology NAS, and have no idea how you have installed homebridge, so cannot help you with that.

**Closed** 2022-05-30 13:42 UTC
Labels: bug
