### ISSUE TITLE
Problems controlling lights on hood

### ISSUE THREAD

**Issue by cstromme** [thoukydides/homebridge-homeconnect#71] opened 2022-01-25 08:51 UTC
#### Description of Issue
We moved to a new house in November. In our old house we had a Siemens hood that we controlled the lights alongside the other lights in the room using this homebridge plugin. That worked perfectly. With the new hood I'm having a lot of issues where it becomes unresponsive in both the Home app and in the Homebridge UI. It doesn't necessarily show as not being reachable, sometimes it just lists itself as on or off and allows me to toggle it, but it doesn't seem to reach the hood itself. There are no errors in the logs. The hood is also accessible in the HomeConnect app. I even got an installer here to replace the wifi module in the hood before I realised that it was still accessible in the HomeConnect app.

Differences between the previous hood and house and now:
1. The hood and the cooktop was connected through wifi, but I disconnected them and the problem persists.
2. We have many more HomeConnect devices now. Tried removing two of them to see if that would help, but the problem is still there. Also I do not see any rate limit messages in the logs.

#### Plugin Version
Every version since we moved which was November 2021.

#### Home Connect Appliance(s)
Siemens Hood LC97FVW61S/01

#### Log File
No log entries when trying to turn on/off the lights. Even with debug logging turned on.

**Comment by cstromme** [comment] 2022-01-25 08:54
These are all the log outputs I could find from this morning related to the hood (Ventilator). Moved to hb-service so a few restarts in here.

> [1/25/2022, 9:34:39 AM] [homebridge-homeconnect] [Ventilator] Siemens Hood (E-Nr: LC97FVW61S/01)
> [1/25/2022, 9:34:39 AM] [homebridge-homeconnect] [Ventilator] The appliance is offline
> [1/25/2022, 9:34:39 AM] [homebridge-homeconnect] [Ventilator] GET status
> [1/25/2022, 9:36:52 AM] [homebridge-homeconnect] [Ventilator] Siemens Hood (E-Nr: LC97FVW61S/01)
> [1/25/2022, 9:38:24 AM] [homebridge-homeconnect] Connecting accessory 'Ventilator'
> [1/25/2022, 9:38:24 AM] [homebridge-homeconnect] [Ventilator] Siemens Hood (E-Nr: LC97FVW61S/01)
> [1/25/2022, 9:38:24 AM] [homebridge-homeconnect] [Ventilator] Event START (0 items)
> [1/25/2022, 9:38:24 AM] [homebridge-homeconnect] [Ventilator] Connected, so reading appliance state...
> [1/25/2022, 9:38:24 AM] [homebridge-homeconnect] [Ventilator] Cache loaded (9 entries)
> [1/25/2022, 9:38:24 AM] [homebridge-homeconnect] [Ventilator] Cache 'Appliance power' [nb-NO, updated 916039 seconds ago] is too old
> [1/25/2022, 9:38:24 AM] [homebridge-homeconnect] [Ventilator] Cache 'Appliance fan' [nb-NO, updated 916039 seconds ago] is too old
> [1/25/2022, 9:38:24 AM] [homebridge-homeconnect] [Ventilator] Cache 'Appliance settings' [nb-NO, updated 916039 seconds ago] is too old
> [1/25/2022, 9:44:38 AM] [homebridge-homeconnect] Connecting accessory 'Ventilator'
> [1/25/2022, 9:44:38 AM] [homebridge-homeconnect] [Ventilator] Siemens Hood (E-Nr: LC97FVW61S/01)
> [1/25/2022, 9:44:38 AM] [homebridge-homeconnect] [Ventilator] Cache loaded (9 entries)
> [1/25/2022, 9:44:38 AM] [homebridge-homeconnect] [Ventilator] Cache 'Appliance power' [nb-NO, updated 916413 seconds ago] is too old
> [1/25/2022, 9:44:38 AM] [homebridge-homeconnect] [Ventilator] Cache 'Appliance fan' [nb-NO, updated 916413 seconds ago] is too old
> [1/25/2022, 9:44:38 AM] [homebridge-homeconnect] [Ventilator] Cache 'Appliance settings' [nb-NO, updated 916413 seconds ago] is too old
> [1/25/2022, 9:44:38 AM] [homebridge-homeconnect] [Ventilator] Event STOP (0 items)
> [1/25/2022, 9:44:38 AM] [homebridge-homeconnect] [Ventilator] Events may have been missed; treating appliance as disconnected
> [1/25/2022, 9:44:39 AM] [homebridge-homeconnect] [Ventilator] Event STOP (0 items)
> [1/25/2022, 9:44:39 AM] [homebridge-homeconnect] [Ventilator] Events may have been missed; treating appliance as disconnected
> [1/25/2022, 9:44:39 AM] [homebridge-homeconnect] [Ventilator] Event STOP (0 items)
> [1/25/2022, 9:44:39 AM] [homebridge-homeconnect] [Ventilator] Events may have been missed; treating appliance as disconnected
> [1/25/2022, 9:44:39 AM] [homebridge-homeconnect] [Ventilator] Event START (0 items)
> [1/25/2022, 9:44:39 AM] [homebridge-homeconnect] [Ventilator] Connected, so reading appliance state...
> [1/25/2022, 9:44:39 AM] [homebridge-homeconnect] [Ventilator] The appliance is offline
> [1/25/2022, 9:44:39 AM] [homebridge-homeconnect] [Ventilator] GET status
> [1/25/2022, 9:44:39 AM] [homebridge-homeconnect] [Ventilator] Error: The appliance is offline
> [1/25/2022, 9:44:39 AM] [homebridge-homeconnect] [Ventilator] Ignoring appliance state read due to disconnection: The appliance is offline
> [1/25/2022, 9:44:39 AM] [homebridge-homeconnect] [Ventilator] Appliance disconnected; abandoning 4 pending reads
> [1/25/2022, 9:48:42 AM] [homebridge-homeconnect] Connecting accessory 'Ventilator'
> [1/25/2022, 9:48:42 AM] [homebridge-homeconnect] [Ventilator] Siemens Hood (E-Nr: LC97FVW61S/01)
> [1/25/2022, 9:48:42 AM] [homebridge-homeconnect] [Ventilator] Cache loaded (9 entries)
> [1/25/2022, 9:48:42 AM] [homebridge-homeconnect] [Ventilator] Cache 'Appliance power' [nb-NO, updated 916657 seconds ago] is too old
> [1/25/2022, 9:48:42 AM] [homebridge-homeconnect] [Ventilator] Cache 'Appliance fan' [nb-NO, updated 916657 seconds ago] is too old
> [1/25/2022, 9:48:42 AM] [homebridge-homeconnect] [Ventilator] Cache 'Appliance settings' [nb-NO, updated 916656 seconds ago] is too old
> [1/25/2022, 9:52:01 AM] [homebridge-homeconnect] [Ventilator] Siemens Hood (E-Nr: LC97FVW61S/01)
> 
>

**Comment by thoukydides** [comment] 2022-01-25 09:09
That partial log indicates that the connections between the Hood and the Home Connect servers, and between the Home Connect servers and this plugin, are not reliable. I have not been seeing any similar issues over the last week (see https://www.thouky.co.uk/homeconnect.html) so this suggests that the problem is with your internet connection.

Where possible, the Home Connect app communicates directly with the appliance via the local Wi-Fi within your house.  It only reverts to using the Home Connect servers and your internet connection when you are away from home. (It is also worth noting that the Home Connect app does not use the public API, so it may also be using different servers.)

I suggest that when you next encounter this problem you try switching off the Wi-Fi on your phone and they seeing whether the Home Connect app is still able to control the Hood. Also, within the Home Connect app go to the Settings for the Hood, and check the Network section to ensure that it shows all three green lines between the appliance, cloud, and phone.

Based on these symptoms it is extremely unlikely that the issue is with this plugin, or that there is anything that I can do to improve the situation. However, if the Home Connect app does not show any problems when connected via the cellular network rather than Wi-Fi, and it shows the appliance fully connected to the network, then it may be worth running homebridge in debug mode (using the `-D` command line switch) and providing a more complete log. This will show the individual requests to the Home Connect servers and whether each returned an error, so may give a little more insight.

**Comment by cstromme** [comment] 2022-01-25 09:12
I tried now and it shows all 3 lines as green for the hood, but if I switch off wifi the HomeConnect app can't connect to It either.

**Comment by cstromme** [comment] 2022-01-25 09:15
I just toggled "Connection to server" to off. Then went back in and turned it on. And now it seems to connect through outside access in the HomeConnect app as well as this plugin. Crossing my fingers it'll remain stable!

**Comment by thoukydides** [comment] 2022-01-25 09:23
Thank you for the update. Hopefully that has fixed the problem for you... although if you have already tried steps like having the hood's Wi-Fi module replaced I suspect that the connection is likely to fail again.

If you see the same issue again then turning off the Wi-Fi on your phone and testing with the Home Connect app should be the first thing to try.  Unless that works reliably via the Home Connect cloud servers there is not much point investigating issues with third-party applications like this plugin.

I am going to close this issue for now. However, if you are able to reproduce the problem when the Home Connect app is working remotely then please re-open the issue and provide a debug log.

**Closed by thoukydides** 2022-01-25 09:23 UTC
Labels: bug

**Comment by thoukydides** [comment] 2022-01-25 09:34
One final suggestion - since the symptoms suggest that your internet connection might not be entirely reliable, it may be worth setting up something like https://www.thinkbroadband.com/broadband/monitoring/quality to monitor the connection (unless you already have something similar).

**Comment by cstromme** [comment] 2022-01-25 09:49
Thanks! I'll try it out, but I haven't seen any other issues and my UniFi system isn't reporting any issues either. I have a sneaking suspicion that something *was* wrong with the previous wifi module, and that the only problem after changing that was solved by toggling this switch on and off. But time will tell! 😊
