### ISSUE TITLE
connection with oath doesn't work

### ISSUE THREAD

**Issue by giuseppeboccolato** [thoukydides/homebridge-homeconnect#299] opened 2024-09-22 03:55 UTC
### Description of Issue

when I try to authorise the app to access fiscal units data, I don't get asked username and psw but only the username and soon later I get this answer:

{
  "error": "access_denied",
  "error_description": "login session expired"
}

### Expected Behaviour

I expected to be asked to login and authorise the app

### Steps to Reproduce

I did 2 times all from scratch, I opened a new dev account, I recreated the app following the guideline and I google it, and looked on reddit, no solution worked

### Plugin Version

1.04

### Environment

- OS: homebrided, browser to access to it, Safari on MacOs
- Node:
- Homebridge: 1.04

### Diagnostic Checks

- [ ] Home Connect app is able to control the appliance with Wi-Fi disabled.
- [ ] Home Connect app shows three green lines in the Network section of the appliance Settings.
- [ ] Unofficial [Home Connect Server Status](https://homeconnect.thouky.co.uk) shows servers up and no recent errors.
- [ ] Searched for [previously reported issues](https://github.com/thoukydides/homebridge-homeconnect/issues?q=is%3Aissue) and no similar ones found.
- [X] Checked the [Home Connect API errors](https://api-docs.home-connect.com/general?#api-errors) and [authorisation errors](https://api-docs.home-connect.com/authorization?#authorization-errors) documentation.

### Log File

```shell
{
  "error": "access_denied",
  "error_description": "login session expired"
}
```

### Configuration

```json
https://api.home-connect.com/security/oauth/device_verify?user_code=1234-5678
```

### Additional Information

none

**Comment by thoukydides** [comment] 2024-09-22 07:17
Duplicate of #298.

This is a bug in the Home Connect authorisation servers. Set English as the preferred language in your browser.

**Closed** 2024-09-22 07:17 UTC
