### ISSUE TITLE
Change color on Bosch DWF97RW61 not possible

### ISSUE THREAD

**Issue by JornDL** [thoukydides/homebridge-homeconnect#54] opened 2021-05-04 04:14 UTC
#### Description of Issue
I have both a dishwasher and a hood from Bosch.
They both support changing the colors on the ambient light.
With this plugin I can only change the colors in HomeKit on the dishwasher but not on my hood.

#### Plugin Version
v0.23.0

#### Home Connect Appliance(s)
Bosch Hood DWF97RW61

#### HomeKit App(s)
HomeKit, Eve

**Comment by thoukydides** [comment] 2021-05-04 04:27
Please can you clarify whether the issue is that no HomeKit service is created for the Hood's ambient light, or that the light does not respond correctly when controlled?

If the problem is that no HomeKit service is created then it is most likely due to the Home Connect API not supporting the ambient light in that particular appliance. This would be indicated in the Homebridge log file by a `Does not support Ambient Light` message. If that is the case then there is nothing that can be done in this plugin to support it.

Please provide a complete Homebridge log with debug enabled (using the `-D` command line switch), starting from when Homebridge is first started.

**Comment by JornDL** [comment] 2021-05-04 04:52
Hi

Thanks for the quick response and for your work on this great plugin.

Attached my log.

I can control (on/off) both my functional light and ambient light on my hood from the Apple HomeKit app.
I can control (on/off/color) on my dishwasher from the Apple HomeKit app.

But the hood supports changing color as I can do this directly from the HomeConnect app itself.

Screenshots from the Apple app (dishwasher and hood):
***@***.***D740B2.144B1420][Et billede, der indeholder tekst, iPod  Automatisk genereret beskrivelse]

BR Jørn Dalgård Larsen

Fra: Alexander Thoukydides ***@***.***>
Svar til: thoukydides/homebridge-homeconnect ***@***.***>
Dato: tirsdag den 4. maj 2021 kl. 06.27
Til: thoukydides/homebridge-homeconnect ***@***.***>
Cc: Jørn Dalgård Larsen ***@***.***>, Author ***@***.***>
Emne: Re: [thoukydides/homebridge-homeconnect] Change color on Bosch DWF97RW61 not possible (#54)


Please can you clarify whether the issue is that no HomeKit service is created for the Hood's ambient light, or that the light does not respond correctly when controlled?

If the problem is that no HomeKit service is created then it is most likely due to the Home Connect API not supporting the ambient light in that particular appliance. This would be indicated in the Homebridge log file by a Does not support Ambient Light message. If that is the case then there is nothing that can be done in this plugin to support it.

Please provide a complete Homebridge log with debug enabled (using the -D command line switch), starting from when Homebridge is first started.

**Comment by thoukydides** [comment] 2021-05-04 05:43
Thank you for the response @JornDL. Unfortunately, I cannot find either the log file or screenshot attached.

If the Home app is not showing a colour control for the Hood appliance then that is almost certainly due to the Home Connect API not supporting the `BSH.Common.Setting.AmbientLightColor` setting. The public API frequently does not support all of the features that the Home Connect app does. The log file should reveal whether this is the case (if captured with `-D` debug enabled). It might be worth checking whether your Hood is running the latest firmware since new API capabilities are often added in firmware updates.

If the log file doesn’t provide the answer then one of the cache files that the plugin saves in the `~/.homebridge/homebridge-homeconnect/persist` directory records the raw API response when asked for the appliance’s settings. I will be able to give you the filename once I see the log file. (Do **NOT** attach the `94a08da1fecbb6e8b46990538c7b50b2` file to this issue since it stores your OAuth credentials; see [Files Storing Plugin State](https://github.com/thoukydides/homebridge-homeconnect/wiki/Files).)

**Comment by JornDL** [comment] 2021-05-04 05:50
Hi 

Here you have my log file.
[homebridge log.docx](https://github.com/thoukydides/homebridge-homeconnect/files/6419176/homebridge.log.docx)

**Comment by thoukydides** [comment] 2021-05-04 07:11
Thank you @JornDL for the log file.

`BSH.Common.Setting.AmbientLightColor` has not been reported as a current setting for the Hood appliance. However, I suspect that this is because the ambient light was off when the log file was captured (as indicated by `BSH.Common.Setting.AmbientLightEnabled` being set to `false`). Some appliances only report the settings that are relevant in their current operating state.

However, when the plugin was first started it should have tried switching the ambient light on to check for any additional settings. The result of this would have been cached, which is why it is not visible in this log file. However, it is possible that something went wrong with that process, and due to the cache the plugin is not trying again until the cache expires (after 24 hours) and Homebridge is restarted. One possibility is that the appliance had been manually controlled just before starting the plugin for the first time, and that temporarily blocked remote control via the API.

If you look in `~/.homebridge/homebridge-homeconnect/persist` (or the corresponding configuration directory for your Homebridge instance) you should have a file called `a7ea3482f629e36887fcdc09d8d9b2f4` (this is the MD5 hash of `BOSCH-DWF97RW61-68A40E5B0B94 cache`). This is the cache of API responses describing the Hood appliance's capabilities.

Please can you provide a copy of the existing `a7ea3482f629e36887fcdc09d8d9b2f4` file. This will show what the API reported during the initial attempt to discover the appliance's capabilities.

If you can spare some extra time to investigate this issue then a couple of extra tests would be helpful...

Firstly, force the plugin to re-read the appliance's capabilities to see whether that is failing for some reason (or it might work this time):
  1. Stop Homebridge.
  2. Delete the `a7ea3482f629e36887fcdc09d8d9b2f4`  cache file.
  3. If you have controlled the Hood recently (either on the appliance, or via the Home Connect app) then wait a couple of minutes to ensure that the appliance re-enables remote control.
  4. Restart Homebridge (with `-D` for debug logging).
  5. Please provide a copy of this Homebridge log file and the new `a7ea3482f629e36887fcdc09d8d9b2f4`  cache file.

Secondly, if the ambient light colour support is still not discovered then it would be worth manually switching on the ambient light and trying again:
  1. Stop Homebridge.
  2. Delete the `a7ea3482f629e36887fcdc09d8d9b2f4`  cache file.
  3. Switch on the ambient light on the Hood itself.
  4. Wait a couple of minutes to ensure that the appliance re-enables remote control.
  5. Restart Homebridge (with `-D` for debug logging).
  6. Please provide a copy of this Homebridge log file and the new `a7ea3482f629e36887fcdc09d8d9b2f4`  cache file.

Unfortunately, I do not have access to a Hood that supports Home Connect so cannot try any of this myself. I rely on people like you providing information about how the appliances behave. They often don't behave how I would expect from the API documentation...

**Comment by JornDL** [comment] 2021-05-04 08:24
Hi

Here you will find my a7ea3482f629e36887fcdc09d8d9b2f4 file.
I will try to find the time later for the other tests you mentioned.
[a7ea3482f629e36887fcdc09d8d9b2f4.zip](https://github.com/thoukydides/homebridge-homeconnect/files/6419820/a7ea3482f629e36887fcdc09d8d9b2f4.zip)

**Comment by thoukydides** [comment] 2021-05-04 08:49
Thank you for the cache file. This confirms that the API only reported support for `BSH.Common.Setting.AmbientLightEnabled` and `BSH.Common.Setting.AmbientLightBrightness`. As a result the plugin did not attempt to read details of any colour support.

I think this leaves the following possibilities:
1. The plugin was unable to switch the ambient light on when it was first started, e.g. due to the Hood being controlled manually or connection problems, which prevented it checking whether that made any additional settings available.
2. The Hood or Home Connect API took longer to respond to switching on the ambient light than the plugin allowed, so any settings related to the ambient light colour were not visible by the time the plugin checked them. This is actually quite likely - I had to add an extra 1 second delay after switching on some appliances before reading the list of programs that they supported.
3. The API does not support control of the ambient light colour for that appliance.

The other tests that I outlined should distinguish between these possibilities, and in the case of 2 the required delay that might be required.

**Comment by thoukydides** [comment] 2021-05-04 17:14
After carefully reviewing the implementation I think I have spotted a potential race condition with the way that the colour support for ambient lights was being determined.

If the ambient light is off when the plugin is started for the first time (or after the cached values are more than 24 hours old) then it will temporarily switch the ambient light on. The code was then relying on the Home Connect servers providing an event for any additional settings that are available (i.e. the colour support) before returning the result of the request that turned the light on. This has been the case in all logs that I have inspected, but it is almost certainly not safe to rely on that behaviour since they are completely independent `https` connections and hence are unsynchronised.

This should be fixed in v0.23.1. The code now explicitly queries the ambient light colour settings after getting confirmation that the light has been switched on.

If you try this new version then it will still be necessary to delete the `a7ea3482f629e36887fcdc09d8d9b2f4` cache file first, otherwise it won't try to re-read the appliance's capabilities.

**Comment by JornDL** [comment] 2021-05-04 17:50
Hi
I will try this tomorrow and get back with the results.

**Comment by JornDL** [comment] 2021-05-05 03:12
Hi

I tried both with the hood and dishwasher off and also on.

Now it is not even possible to switch on/off the ambient light on the hood.
Also, now I can't switch on/off/color on my dishwasher.

Included my boot-log
[homebridge-homeconnect log.docx](https://github.com/thoukydides/homebridge-homeconnect/files/6424911/homebridge-homeconnect.log.docx)

**Comment by thoukydides** [comment] 2021-05-05 06:53
Sorry, that was a silly error.
Should be fixed in v0.23.2.

**Comment by JornDL** [comment] 2021-05-06 04:11
Hi

I can confirm that everything is working fine now.

To be sure, I reset the homebridge and added it to homekit again.

Thanks again for this great plugin and you time :-)

**Comment by thoukydides** [comment] 2021-05-06 04:37
That's great news.

Thank you for reporting the issue, the helpful log files, and your patience.

**Closed** 2021-05-06 04:37 UTC
Labels: bug
