### ISSUE TITLE
Warning message and accessories not showing

### ISSUE THREAD

**Issue by Juanpermon** [thoukydides/homebridge-homeconnect#269] opened 2024-04-04 12:01 UTC
### Plugin Version

0.41.3

### Home Connect Appliance(s)

All of them

### Log File

```shell
[4/4/2024, 2:00:15 PM] [HomeConnect] Waiting 1 hour 8 minutes before issuing Home Connect API request
```

### Additional Information

During plugin configuration I can't find the AUTHORISE button, could that be the reason of the warning message?

**Comment by thoukydides** [comment] 2024-04-04 12:22
Your report does not provide anywhere near enough information to provide a useful diagnosis.

The `Waiting 1 hour 8 minutes before issuing Home Connect API request` message is caused by hitting a [Home Connect API rate limit](https://api-docs.home-connect.com/general/#rate-limiting). There are six different limits, and many reasons why those limits could be exceeded. It may be perfectly normal and expected, with this plugin needing to issue a lot of requests to discover details of your appliances and their supported features and options. Alternatively, there could be something going wrong.

There are also many possible reasons why you might not be presented with the `AUTHORISE` button. I am not going to even start guessing about that. However, I will note that I am not seeing any issues myself - I can authorise a new installation without any problems - so it is most likely to be due to something wrong in your configuration.

Please provide a full log file, not just a single line. Please also ensure that debug logging is enabled.

**Comment by thoukydides** [comment] 2024-04-27 08:30
I am closing this issue because no useful information has been provided in the 3 weeks since it was created.

**Closed by thoukydides** 2024-04-27 08:30 UTC
Labels: bug
