### ISSUE TITLE
Error loading plugin, readablestream is not defined

### ISSUE THREAD

**Issue by Praktiker** [thoukydides/homebridge-homeconnect#239] opened 2024-01-26 17:21 UTC
### Description of Issue

Plugin worked a couple of weeks before but since some update in between it stopped working:
26.1.2024, 18:00:04homeconnectbridge stopping
26.1.2024, 18:00:09Homeconnect Bridge starting
26.1.2024, 18:00:16Homeconnect BridgeFEHLERError loading plugin "homebridge-homeconnect"
26.1.2024, 18:00:16Homeconnect BridgeFEHLERReadableStream is not defined
26.1.2024, 18:00:16Homeconnect BridgeFEHLERReferenceError: ReadableStream is not defined
    at Object.<anonymous> (/var/lib/hoobs/homeconnectbridge/node_modules/undici/lib/fetch/response.js:516:3)
    at Module._compile (node:internal/modules/cjs/loader:1198:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
    at Module.load (node:internal/modules/cjs/loader:1076:32)
    at Function.Module._load (node:internal/modules/cjs/loader:911:12)
    at Module.require (node:internal/modules/cjs/loader:1100:19)
    at require (node:internal/modules/cjs/helpers:119:18)
    at Object.<anonymous> (/var/lib/hoobs/homeconnectbridge/node_modules/undici/lib/fetch/index.js:11:5)
    at Module._compile (node:internal/modules/cjs/loader:1198:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
    at Module.load (node:internal/modules/cjs/loader:1076:32)
    at Function.Module._load (node:internal/modules/cjs/loader:911:12)
    at Module.require (node:internal/modules/cjs/loader:1100:19)
    at require (node:internal/modules/cjs/helpers:119:18)
    at Object.<anonymous> (/var/lib/hoobs/homeconnectbridge/node_modules/undici/index.js:97:19)
    at Module._compile (node:internal/modules/cjs/loader:1198:14)
26.1.2024, 18:00:16Homeconnect BridgeWARNUNGNo plugins installed.
26.1.2024, 18:00:16Homeconnect BridgeLoading 1 platforms...
26.1.2024, 18:00:16Homeconnect BridgeBridge is running on port 51866.

### Expected Behaviour

Should work as before

### Steps to Reproduce

I installed the plugin and followed all needed steps. Even after reinstall, same thing happens

### Plugin Version

0.39.1

### Environment

- OS: PI
- Node: 16.20.2
- Homebridge: 1.7.0 (but 1.6.0 had the same issue)
HOOBS 4.3.1 (error appeared also on 4.3.0)

### Home Connect Appliance(s)

Siemens washing Maschine WM14UR5EM2/53

### HomeKit App(s)

Apple home

### Diagnostic Checks

- [X] Home Connect app is able to control the appliance with Wi-Fi disabled.
- [X] Home Connect app shows three green lines in the Network section of the appliance Settings.
- [X] Unofficial [Home Connect Server Status](https://homeconnect.thouky.co.uk) shows servers up and no recent errors.
- [X] Searched for [previously reported issues](https://github.com/thoukydides/homebridge-homeconnect/issues?q=is%3Aissue) and no similar ones found.
- [X] Checked the [Home Connect API errors](https://api-docs.home-connect.com/general?#api-errors) and [authorisation errors](https://api-docs.home-connect.com/authorization?#authorization-errors) documentation.

### Log File

```shell
26.1.2024, 18:00:04homeconnectbridge stopping
26.1.2024, 18:00:09Homeconnect Bridge starting
26.1.2024, 18:00:16Homeconnect BridgeFEHLERError loading plugin "homebridge-homeconnect"
26.1.2024, 18:00:16Homeconnect BridgeFEHLERReadableStream is not defined
26.1.2024, 18:00:16Homeconnect BridgeFEHLERReferenceError: ReadableStream is not defined
    at Object.<anonymous> (/var/lib/hoobs/homeconnectbridge/node_modules/undici/lib/fetch/response.js:516:3)
    at Module._compile (node:internal/modules/cjs/loader:1198:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
    at Module.load (node:internal/modules/cjs/loader:1076:32)
    at Function.Module._load (node:internal/modules/cjs/loader:911:12)
    at Module.require (node:internal/modules/cjs/loader:1100:19)
    at require (node:internal/modules/cjs/helpers:119:18)
    at Object.<anonymous> (/var/lib/hoobs/homeconnectbridge/node_modules/undici/lib/fetch/index.js:11:5)
    at Module._compile (node:internal/modules/cjs/loader:1198:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
    at Module.load (node:internal/modules/cjs/loader:1076:32)
    at Function.Module._load (node:internal/modules/cjs/loader:911:12)
    at Module.require (node:internal/modules/cjs/loader:1100:19)
    at require (node:internal/modules/cjs/helpers:119:18)
    at Object.<anonymous> (/var/lib/hoobs/homeconnectbridge/node_modules/undici/index.js:97:19)
    at Module._compile (node:internal/modules/cjs/loader:1198:14)
26.1.2024, 18:00:16Homeconnect BridgeWARNUNGNo plugins installed.
26.1.2024, 18:00:16Homeconnect BridgeLoading 1 platforms...
26.1.2024, 18:00:16Homeconnect BridgeBridge is running on port 51866.
```

### Configuration

```json
{
    "platform": "HomeConnect",
    "clientid": "F........12C"
}
```

**Comment by thoukydides** [comment] 2024-01-26 17:49
Duplicate of #195 and #239.

> HOOBS 4.3.1 (error appeared also on 4.3.0)

This is a Homebridge plugin, not a HOOBS plugin. Any issues using it with HOOBS should be referred to HOOBS support.

However, there is an obvious problem in this case...

> Node: 16.20.2

Your version of Node.JS is too old. This plugin requires Node.JS 18.x LTS or 20.x LTS, in compliance with the [Homebridge Verified plugin](https://github.com/homebridge/homebridge/wiki/Verified-Plugins) requirements.

Node.JS 18.0.0 exposed `ReadableStream` on the global object, so that is the earliest compatible version. However, I recommend using the latest 18.x or 20.x release.

**Closed by thoukydides** 2024-01-26 17:49 UTC
Labels: duplicate
