### ISSUE TITLE
Warning from the characteristic 'Brightness': characteristic was supplied illegal value: number 0 exceeded minimum of 25

### ISSUE THREAD

**Issue by floriangrotz** [thoukydides/homebridge-homeconnect#84] opened 2022-04-11 14:15 UTC
#### Description of Issue
Error in Log 

#### Plugin Version
0.24.1

#### Home Connect Appliance(s)
Siemens Hood (E-Nr: LC98KLV60/03)

#### HomeKit App(s)
n/a

#### Diagnostic Checks
n/a

#### Log File
[11/04/2022, 16:08:22] [homebridge-homeconnect] This plugin generated a warning from the characteristic 'Brightness': characteristic was supplied illegal value: number 0 exceeded minimum of 25. See https://git.io/JtMGR for more info.
[11/04/2022, 16:08:22] [homebridge-homeconnect] Error: 
    at Brightness.Characteristic.characteristicWarning (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2142:105)
    at Brightness.Characteristic.validateUserInput (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2045:14)
    at Brightness.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1582:21)
    at step (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:143:27)
    at Object.next (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:124:57)
    at /usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:117:75
    at new Promise (<anonymous>)
    at __awaiter (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:113:16)
    at Brightness.Characteristic.handleGetRequest (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/dist/lib/Characteristic.js:689:38)
    at Brightness.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2207:22)
[11/04/2022, 16:08:23] [HomeConnect] [Hood] Cache loaded (6 entries)

**Comment by thoukydides** [comment] 2022-04-11 14:34
This plugin makes a special case of Hood appliances because they are the one type of appliance for which HomeKit provides appropriate characteristics and services.

Unfortunately, I do not have a Home Connect Hood appliance, and the Home Connect Developer site does not provide a simulator for Hood appliances. Hence, I have coded the support without any testing by myself, and rely entirely on owners of such appliances trying builds and reporting the results.

To give me a clue as to where to start investigating you will need to provide a full Homebridge log with debug enabled (using the `-D` command line option). Not just those few lines.

Please also provide a copy of the cache file for your Hood appliance from the `.homebridge/homebridge-homeconnect/persist` directory. The minimum value of the HomeKit `Brightness` characteristic is set based on the constraints indicated by the Home Connect API - usually 10% to 100%. (Do NOT post/share the `94a08da1fecbb6e8b46990538c7b50b2` file since that contains your OAuth tokens!)

**Comment by floriangrotz** [comment] 2022-04-11 16:54
I found as well - https://api-docs.home-connect.com/settings?#functional-light-brightness 

![IMG_6810](https://user-images.githubusercontent.com/63972904/162789522-ac221e33-6e52-4eea-a14a-c30a0e6fc762.jpg)

/var/lib/homebridge/homebridge-homeconnect/persist $ cat 0e350f2238d51e52a0d933171ea8dfc1
{"key":"SIEMENS-LC98KLV60-68A40E306CE2 cache","value":{"Appliance fan":{"value":[{"key":"Cooking.Common.Program.Hood.Automatic","name":"Automatic mode","constraints":{"execution":"startonly"}},{"key":"Cooking.Common.Program.Hood.Venting","name":"Fan setting","constraints":{"execution":"startonly"}},{"key":"Cooking.Common.Program.Hood.DelayedShutOff","name":"Fan run-on","constraints":{"execution":"startonly"}}],"preferred":"en-GB","updated":1649615655766},"Appliance power":{"value":{"name":"Power status","key":"BSH.Common.Setting.PowerState","constraints":{"allowedvalues":["BSH.Common.EnumType.PowerState.Off","BSH.Common.EnumType.PowerState.On"],"displayvalues":["Off","On"],"access":"readWrite"},"type":"BSH.Common.EnumType.PowerState","displayvalue":"Off","value":"BSH.Common.EnumType.PowerState.Off"},"preferred":"en-GB","updated":1649615655777},"Appliance settings":{"value":[{"key":"BSH.Common.Setting.PowerState","value":"BSH.Common.EnumType.PowerState.Off","name":"Power status","displayvalue":"Off"},{"key":"Cooking.Common.Setting.Lighting","value":false,"name":"Work light"},{"key":"Cooking.Common.Setting.LightingBrightness","value":10,"unit":"%","name":"Brightness"}],"preferred":"en-GB","updated":1649615655953},"Appliance fan manual program":{"value":{"key":"Cooking.Common.Program.Hood.Venting","options":[{"key":"Cooking.Common.Option.Hood.VentingLevel","type":"Cooking.Hood.EnumType.Stage","constraints":{"allowedvalues":["Cooking.Hood.EnumType.Stage.FanStage01","Cooking.Hood.EnumType.Stage.FanStage02","Cooking.Hood.EnumType.Stage.FanStage03"],"displayvalues":["1","2","3"],"default":"Cooking.Hood.EnumType.Stage.FanStage02"},"name":"Fan setting"},{"key":"Cooking.Common.Option.Hood.IntensiveLevel","type":"Cooking.Hood.EnumType.IntensiveStage","constraints":{"allowedvalues":["Cooking.Hood.EnumType.IntensiveStage.IntensiveStage1","Cooking.Hood.EnumType.IntensiveStage.IntensiveStage2"],"displayvalues":["Boost","PowerBoost"]},"name":"Intensive settings"}],"name":"Fan setting"},"preferred":"en-GB","updated":1649615656049},"Appliance Functional Light brightness":{"value":{"name":"Brightness","key":"Cooking.Common.Setting.LightingBrightness","constraints":{"min":10,"max":100,"access":"readWrite"},"unit":"%","type":"Double","value":72},"preferred":"en-GB","updated":1649615657615},"Functional Light":{"value":{"on":{"key":"Cooking.Common.Setting.Lighting"},"brightness":{"name":"Brightness","key":"Cooking.Common.Setting.LightingBrightness","constraints":{"min":10,"max":100,"access":"readWrite"},"unit":"%","type":"Double","value":72}},"preferred":"en-GB","updated":1649615657947}}}

**Comment by thoukydides** [comment] 2022-04-11 17:20
It is curious that homebridge is reporting a minimum value of 25 for this characteristic rather than 10%. That doesn't match either the default range for the Homebridge `Characteristic.Brightness` (0) or the range that this plugin will configure based on the Home Connect API response (10).

Hopefully the Homebridge debug log will provide more clues...

**Comment by floriangrotz** [comment] 2022-04-11 17:31
Have you checked https://git.io/JtMGR ?

[11/04/2022, 19:17:51] [HomeConnect] Home Connect request #9: GET https://api.home-connect.com/api/homeappliances/SIEMENS-LC98KLV60/status
[11/04/2022, 19:17:51] [homebridge-homeconnect] This plugin generated a warning from the characteristic 'Brightness': characteristic was supplied illegal value: number 0 exceeded minimum of 25. See https://git.io/JtMGR for more info.
[11/04/2022, 19:17:51] [homebridge-homeconnect] Error: 
    at Brightness.Characteristic.characteristicWarning (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2142:105)
    at Brightness.Characteristic.validateUserInput (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2045:14)
    at Brightness.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1582:21)
    at step (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:143:27)
    at Object.next (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:124:57)
    at /usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:117:75
    at new Promise (<anonymous>)
    at __awaiter (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:113:16)
    at Brightness.Characteristic.handleGetRequest (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/dist/lib/Characteristic.js:689:38)
    at Brightness.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2207:22)
[11/04/2022, 19:17:52] [HomeConnect] [Hood] Cache loaded (6 entries)
[11/04/2022, 19:17:52] [HomeConnect] [Hood] Cache 'Appliance power' [en-GB, updated 81816 seconds ago]
[11/04/2022, 19:17:52] [HomeConnect] [Hood] Cache 'Appliance fan' [en-GB, updated 81816 seconds ago]
[11/04/2022, 19:17:52] [HomeConnect] [Hood] Cache 'Appliance settings' [en-GB, updated 81816 seconds ago]
[11/04/2022, 19:17:52] [HomeConnect] [Hood] Can be switched off
[11/04/2022, 19:17:52] [HomeConnect] [Hood] Cache 'Appliance fan manual program' [en-GB, updated 81816 seconds ago]
[11/04/2022, 19:17:52] [HomeConnect] [Hood] Fan suppports 3 venting levels + 2 intensive levels + auto mode
[11/04/2022, 19:17:52] [HomeConnect] [Hood]     20% (Cooking.Hood.EnumType.Stage.FanStage01)
[11/04/2022, 19:17:52] [HomeConnect] [Hood]     25% (Cooking.Hood.EnumType.Stage.FanStage02) = Siri 'low'
[11/04/2022, 19:17:52] [HomeConnect] [Hood]     50% (Cooking.Hood.EnumType.Stage.FanStage03) = Siri 'medium'
[11/04/2022, 19:17:52] [HomeConnect] [Hood]     80% (Cooking.Hood.EnumType.IntensiveStage.IntensiveStage1)
[11/04/2022, 19:17:52] [HomeConnect] [Hood]     100% (Cooking.Hood.EnumType.IntensiveStage.IntensiveStage2) = Siri 'high'

**Comment by thoukydides** [comment] 2022-04-11 17:34
Looking again at the stack backtrack from your original log snippet it appears the warning is getting triggered by a read of the HomeKit Brightness characteristic rather that a write - the backtrack starts with a call to `handleGetRequest`.

This could be as simple as a new Brightness characteristic defaulting to 0, and the plugin then configuring the allowed range, resulting in its current value being outside that range. If so, then that should be easy to fix for this specific case since the initial value can be set at the same time as the range.

Let's see what the log file reveals first...

**Comment by thoukydides** [comment] 2022-04-11 18:01
Yes, I did check https://git.io/JtMGR. That does not provide anything insight.

I am still waiting for a full debug log to show what might be triggering this issue. Providing just one extra line before the issue is not helpful.

Also, just to check... what version of Homebridge are you using?
My best attempts to recreate this error with Homebridge 1.4.0 don't reveal any issues.

**Comment by floriangrotz** [comment] 2022-04-11 19:12
Using Homebridge 1.4.0

mit seems to be when I switch the light on and off

![6175A265-D5AD-4242-B837-1777CBA8BBBB](https://user-images.githubusercontent.com/63972904/162811989-11f7c386-098c-4ba8-aa97-56a959b09ce4.jpeg)

**Comment by thoukydides** [comment] 2022-04-11 19:20
Do you mean switching the light on and off using the appliance's physical buttons, or via HomeKit, or the Home Connect app?

That screenshot really doesn't tell me anything useful. I still need to see a full debug log, e.g. to see whether the Home Connect API is reporting a brightness of 0.

I still don't understand why Homebridge is reporting a minimum of 25 though. That aspect is looking like it might be a Homebridge bug...

**Comment by thoukydides** [comment] 2022-04-12 12:05
Despite trying everything that I can think of I am unable to reproduce this problem.

If I explicitly set the Brightness characteristic to an out-of-range value then it gives the expected warning... with Homebridge reporting the correct minimum value of 10 rather than the 25 reported in your log.

Despite careful review of the code for this plugin, for Homebridge, and for HAP-NodeJS, I cannot see anything that would result in either the Brightness being set to an out of range value, or the incorrect `minValue` being reported. (I have however, spotted a few copy-and-paste bugs in the HAP-NodeJS value validation code that I will be reporting...)

Unless further information is provided that gives a clue as to what might be going wrong I am going to ignore this issue. It is just a warning, and is unlikely to affect operation in any way.

**Comment by floriangrotz** [comment] 2022-04-12 18:54
Thx for doing so much effort. I’ve checked logs but that’s all I got.

**Closed** 2022-06-17 09:52 UTC
Labels: bug
