### ISSUE TITLE
Dishwasher turn off after homebridge-homeconnect API error

### ISSUE THREAD

**Issue by Paulxp** [thoukydides/homebridge-homeconnect#78] opened 2022-02-27 16:09 UTC
Hi guys,
my Dishwasher Siemens SMI8YCS01E/01 with software version 2.4-3.3.12.20211004153143 (2.1) automatically turn off after short operation time after manual start from device. 

Homebridge v 1.4.0
NodeJS: [v16.14.0]
homebridge-homeconnect v0.23.7

Homebridge log shows:

[27/02/2022, 16:59:23] [HomeConnect] [Umývačka riadu] Switching appliance on to read program options
[27/02/2022, 16:59:25] [HomeConnect] [Umývačka riadu] On
[27/02/2022, 16:59:41] [HomeConnect] [Umývačka riadu] Program 'Express 60' (Dishcare.Dishwasher.Program.Kurz60) active
[27/02/2022, 16:59:41] [HomeConnect] [Umývačka riadu] Active (Run)
[27/02/2022, 16:59:41] [HomeConnect] [Umývačka riadu] Program has 1 hour 29 minutes remaining
[27/02/2022, 16:59:42] [HomeConnect] [Umývačka riadu] Door closed
[27/02/2022, 17:00:44] [HomeConnect] [Umývačka riadu] Program has 1 hour 28 minutes remaining
[27/02/2022, 17:01:26] [HomeConnect] [Umývačka riadu] Using expired cache result: Timeout waiting for OperationState
[27/02/2022, 17:01:27] [HomeConnect] [Umývačka riadu] **Home Connect API error: Request cannot be performed since OperationState is not Ready [SDK.Error.WrongOperationState]**
[27/02/2022, 17:01:27] [HomeConnect] [Umývačka riadu] SET selected program Dishcare.Dishwasher.Program.Eco50
[27/02/2022, 17:01:27] [HomeConnect] [Umývačka riadu] PUT https://api.home-connect.com/api/homeappliances/010110518272000437/programs/selected
[27/02/2022, 17:01:28] [HomeConnect] [Umývačka riadu] Off
[27/02/2022, 17:01:28] [HomeConnect] [Umývačka riadu] Off
[27/02/2022, 17:01:28] [HomeConnect] [Umývačka riadu] Inactive (Inactive)
[27/02/2022, 17:01:28] [HomeConnect] [Umývačka riadu] No program running
[27/02/2022, 17:01:28] [HomeConnect] [Umývačka riadu] Program 'Express 60' (Dishcare.Dishwasher.Program.Kurz60) inactive

**Comment by thoukydides** [comment] 2022-02-27 19:10
From the few lines of logging that you provided it looks like the plugin is attempting to refresh the list of programs and their options supported by your appliance. It will normally attempt to do that when the plugin is first started... except that if the appliance is disconnected from the Home Connect servers (which could be due to it being switched off or unplugged) then it has to wait until the appliance is connected.

To reliably read the list of programs the appliance has to be on. Additionally, it is only possible to correctly read the options for each program when that program is selected. Hence, the plugin will switch the appliance on (if it is not already on), read the list of supported programs, select each program in turn and read its options, and finally restore the initial power state.

The `Switching appliance on to read program options` log entry implies that this sequence is being started... but that should be followed by a log entry showing `BSH.Common.Setting.PowerState` being set to `BSH.Common.EnumType.PowerState.On`, but that is not shown in your log. Similarly, you say that the plugin is switching the appliance off, but there is no indication of that in the log you provided. In fact, the only instruction that the log shows the plugin issuing was an attempt to select the `Dishcare.Dishwasher.Program.Eco50` program... but the log does not even show whether that was successful.

Lots of other expected log entries are missing, which makes it almost impossible to diagnose what might be going wrong.

If I was to hazard a guess, then a possible scenario is something along the following lines:

1. Appliance is disconnected when homebridge starts, so the plugin waits for the appliance to connect before reading the program details.
2. You switch on the appliance, and quickly start the a Dishcare.Dishwasher.Program.Kurz60` (Express 60) program, which for some reason has a 90 minute duration, before the appliance can connect to the Home Connect servers.
3. The appliance connects to the Home Connect servers, and they notify the plugin that the appliance is now connected. However, the appliance has not yet got around to telling the Home Connect servers that it is switched on and running a program.
4. The plugin reads the appliance's state, and is told that the appliance is connected, but currently switched off and idle.
5. The plugin issues the command to switch the appliance on, during the processing of which...
6. The appliance tells the Home Connect servers that the appliance is switched on and running a program, and they notify the plugin of the state change.
7. The command to switch on the appliance completes successfully (since it was actually already on).
8. The plugin then waits up to 2 seconds for the appliance to indicate that it is `BSH.Common.EnumType.OperationState.Ready` (switched on and idle). However, since you have started a program this state is not reached, resulting in the timeout expiring.
9. The plugin gives up trying to read the options for the appliance's programs, so makes a best effort attempt to restore the appliance's initial state. However, this is the state that the Home Connect servers reported before they received an update from the appliance.
10. The plugin first tries to change the selected program back from `Dishcare.Dishwasher.Program.Kurz60` to `Dishcare.Dishwasher.Program.Eco50`. This is rejected because the program is running.
11. The plugin then tries to restore the initial power state, changing it from `BSH.Common.EnumType.PowerState.On` to `BSH.Common.EnumType.PowerState.Off`, since it thinks it was responsible for switching the appliance on in the first place. Somewhat surprisingly, the appliance accepts this even though there is an active program running.

However, without seeing the detailed log I cannot be sure that this is actually what happened, or attempt to do anything about it.

Please can you provide a longer log file - ideally from when homebridge is (re)started until after the problem has occurred. Do not delete any lines relating to this plugin. The `[Umývačka riadu]` text will not appear on every line that is relevant, so DO NOT filter on that.

Please also provide a more detailed description of the scenario, e.g. is the appliance plugged-in and switched on then homebridge starts, and what sequence and timing of operations you manually performed on the appliance around the time of the problem.

**Comment by thoukydides** [comment] 2022-02-27 19:48
Also, are you able to reproduce this issue reliably?

I have never encountered this issue myself, so unless you can reproduce it on-demand it will not be possible to test any potential fix...

**Comment by thoukydides** [comment] 2022-02-28 06:30
Just realised that you probably posted a non-debug log, which would explain so much missing information. I was confused by the `PUT https://api.home-connect.com/api/homeappliances/010110518272000437/programs/selected` entry, which would normally only appear in a debug log… except in this case it is being reported due to the API error.

So in addition to providing a longer log, please ensure that debug logging is enabled, using the `-D` option on the homebridge command line.

**Comment by Paulxp** [comment] 2022-02-28 06:33
Hi, yes i can reproduce issue anytime. So give me some time, i ll prepare debug log with video :-)

**Comment by thoukydides** [comment] 2022-02-28 09:20
> yes i can reproduce issue anytime. So give me some time, i ll prepare debug log with video :-)

That will be great. Thank you.

Scenarios like this with communicating asynchronous systems can be quite complicated, especially when I only have full visibility/control of one side. I suspect that it should be possible to significantly reduce the occurrence of this problem, but I doubt whether it will be possible to eliminate it completely - there will always be a race condition between the user manually starting a program and the plugin finishing its read of program options and turning the power off. This is unavoidable without changes to the Home Connect API architecture itself.

**Comment by Paulxp** [comment] 2022-03-02 20:01
Hmm, it is interesting but when i tried today to run homebridge in debug mode, i am unable to reproduce issue. Everything works fine now.

**Comment by thoukydides** [comment] 2022-03-03 06:21
> when i tried today to run homebridge in debug mode, i am unable to reproduce issue. Everything works fine now.

That is probably because the plugin has now successfully read and cached the details of all the appliance's programs. It will not try again until the cached values are (at least) 24 hours old and homebridge is restarted.

You can force this to occur sooner by stopping homebridge, deleting the cache files (except for `94a08da1fecbb6e8b46990538c7b50b2` from inside `~/.homebridge/homebridge-homeconnect/persist/`, and restarting homebridge.

The `94a08da1fecbb6e8b46990538c7b50b2` file contains the OAuth token, so don't delete that unless you want to reauthorise the plugin with the Home Connect servers. All of the other cache files are safe to delete.

**Comment by Paulxp** [comment] 2022-03-03 08:49
I have deleted files as you requested, restarted homebridge but issue still cant be reproduced. I leave homebridge in debug mode and hope this situation appears during day

But what is interesting, i see in log file:

03/03/2022, 09:39:16] [HomeConnect] [Umývačka riadu] Event NOTIFY (6 items)
[03/03/2022, 09:39:16] [HomeConnect] [Umývačka riadu] BSH.Common.Root.SelectedProgram=Dishcare.Dishwasher.Program.Eco50 (1 listeners)
[03/03/2022, 09:39:16] [HomeConnect] [Umývačka riadu] **Selected program Dishcare.Dishwasher.Program.Eco50 is not supported by the Home Connect API**
[03/03/2022, 09:39:16] [HomeConnect] [Umývačka riadu] BSH.Common.Option.RemainingProgramTime=14100 seconds (1 listeners)
[03/03/2022, 09:39:16] [HomeConnect] [Umývačka riadu] Dishcare.Dishwasher.Option.IntensivZone=false (0 listeners)
[03/03/2022, 09:39:16] [HomeConnect] [Umývačka riadu] Dishcare.Dishwasher.Option.VarioSpeedPlus=false (0 listeners)
[03/03/2022, 09:39:16] [HomeConnect] [Umývačka riadu] Dishcare.Dishwasher.Option.HygienePlus=false (0 listeners)
[03/03/2022, 09:39:16] [HomeConnect] [Umývačka riadu] BSH.Common.Option.ProgramProgress=0 % (0 listeners)
[03/03/2022, 09:39:16] [HomeConnect] [Umývačka riadu] Program has 3 hours 55 minutes remaining
[03/03/2022, 09:39:16] [HomeConnect] [Umývačka riadu] Event EVENT (1 item)
[03/03/2022, 09:39:16] [HomeConnect] [Umývačka riadu] BSH.Common.Event.ProgramAborted=BSH.Common.EnumType.EventPresentState.Present (2 listeners)

## Aborted program manually in Home Connect APP by me ##

[03/03/2022, 09:39:16] [HomeConnect] [Umývačka riadu] Event Program Aborted
[03/03/2022, 09:39:16] [HomeConnect] [Umývačka riadu] No program running
[03/03/2022, 09:39:17] [HomeConnect] [Umývačka riadu] Event STATUS (1 item)
[03/03/2022, 09:39:17] [HomeConnect] [Umývačka riadu] BSH.Common.Status.OperationState=BSH.Common.EnumType.OperationState.Ready (3 listeners)
[03/03/2022, 09:39:17] [HomeConnect] [Umývačka riadu] Inactive (Ready)

**Comment by thoukydides** [comment] 2022-03-03 09:02
> `Selected program Dishcare.Dishwasher.Program.Eco50 is not supported by the Home Connect API`

That message is due to the Home Connect API sending an event that the program has been selected before the plugin has had the opportunity to read the list of supported programs (and does not have a cached list). 

The message is really indicating that the plugin is not going to bother asking the Home Connect API for details of the program's supported options, because based on the information it has at that time it would not be able to start the program itself. When the plugin does obtain a list of supported programs it will then ask the Home Connect API  for the options supported by each program.

Hence, this is perfectly safe and expected behaviour. I suppose I could suppress (or change) the message in the case where the plugin has not yet obtained the list of supported programs, as opposed to having the list but the current program not being on it. However, this can only happen the first time that the plugin is used (or after deleting the cache files), and it is only a cosmetic issue in the log file.

**Comment by Paulxp** [comment] 2022-03-05 20:15
Hi,
my homebridge was in mode Debug. Dishwasher was turned on 10 times during this period and issue didn't occure. So i have decidec to put Homebridge back in normal operation. This evening, dishwasher was turned off. 

Normal logfile here:

# Dishwasher was turned on physically (manually)
[05/03/2022, 20:39:21] [HomeConnect] [Umývačka riadu] Switching appliance on to read program options
[05/03/2022, 20:39:23] [HomeConnect] [Umývačka riadu] On
[05/03/2022, 20:40:02] [HomeConnect] [Umývačka riadu] Program 'Eco 50' (Dishcare.Dishwasher.Program.Eco50) active
[05/03/2022, 20:40:03] [HomeConnect] [Umývačka riadu] Active (Run)
[05/03/2022, 20:40:03] [HomeConnect] [Umývačka riadu] Program has 3 hours 55 minutes remaining
[05/03/2022, 20:40:03] [HomeConnect] [Umývačka riadu] Door closed
[05/03/2022, 20:41:05] [HomeConnect] [Umývačka riadu] Program has 3 hours 54 minutes remaining
[05/03/2022, 20:41:24] [HomeConnect] [Umývačka riadu] Timeout waiting for OperationState
[05/03/2022, 20:41:24] [HomeConnect] [Umývačka riadu] Cached operation 'program select Dishcare.Dishwasher.Program.Eco50'
# This is moment of automatic poweroff
[05/03/2022, 20:41:26] [HomeConnect] [Umývačka riadu] Off
[05/03/2022, 20:41:26] [HomeConnect] [Umývačka riadu] Off
[05/03/2022, 20:41:26] [HomeConnect] [Umývačka riadu] Inactive (Inactive)
[05/03/2022, 20:41:26] [HomeConnect] [Umývačka riadu] No program running
[05/03/2022, 20:41:26] [HomeConnect] [Umývačka riadu] Program 'Eco 50' (Dishcare.Dishwasher.Program.Eco50) inactive
# This is moment of power on by original Home Connect ios APP
[05/03/2022, 20:42:05] [HomeConnect] [Umývačka riadu] On
[05/03/2022, 20:42:05] [HomeConnect] [Umývačka riadu] Active (Run)
[05/03/2022, 20:42:05] [HomeConnect] [Umývačka riadu] Program has 3 hours 54 minutes remaining
[05/03/2022, 20:43:13] [HomeConnect] [Umývačka riadu] Program has 3 hours 53 minutes remaining
[05/03/2022, 20:44:13] [HomeConnect] [Umývačka riadu] Program has 3 hours 52 minutes remaining
[05/03/2022, 20:45:13] [HomeConnect] [Umývačka riadu] Program has 3 hours 51 minutes remaining
[05/03/2022, 20:46:13] [HomeConnect] [Umývačka riadu] Program has 3 hours 50 minutes remaining
[05/03/2022, 20:47:13] [HomeConnect] [Umývačka riadu] Program has 3 hours 49 minutes remaining
[05/03/2022, 20:48:13] [HomeConnect] [Umývačka riadu] Program has 3 hours 48 minutes remaining
[05/03/2022, 20:49:13] [HomeConnect] [Umývačka riadu] Program has 3 hours 47 minutes remaining
[05/03/2022, 20:50:13] [HomeConnect] [Umývačka riadu] Program has 3 hours 46 minutes remaining
[05/03/2022, 20:51:13] [HomeConnect] [Umývačka riadu] Program has 3 hours 45 minutes remaining
[05/03/2022, 20:52:13] [HomeConnect] [Umývačka riadu] Program has 3 hours 44 minutes remaining
[05/03/2022, 20:53:13] [HomeConnect] [Umývačka riadu] Program has 3 hours 43 minutes remaining
[05/03/2022, 20:54:13] [HomeConnect] [Umývačka riadu] Program has 3 hours 42 minutes remaining
[05/03/2022, 20:55:13] [HomeConnect] [Umývačka riadu] Program has 3 hours 41 minutes remaining
[05/03/2022, 20:56:13] [HomeConnect] [Umývačka riadu] Program has 3 hours 40 minutes remaining
[05/03/2022, 20:57:13] [HomeConnect] [Umývačka riadu] Program has 3 hours 39 minutes remaining
[05/03/2022, 20:58:13] [HomeConnect] [Umývačka riadu] Program has 3 hours 38 minutes remaining
[05/03/2022, 20:59:13] [HomeConnect] [Umývačka riadu] Program has 3 hours 37 minutes remaining

Just let me know if this can help you little bit or one option for good debug is verbose log. I will try it again in debug mode

**Comment by thoukydides** [comment] 2022-03-06 11:50
Unfortunately those log entries do not tell me anything new. They are basically the same as you provided previously.

To have any chance of even properly diagnosing the cause, or devising a possible fix, I really need the (verbose) debug logs - showing the individual requests/responses to the Home Connect servers, and events reported by those servers.

Sorry.

**Comment by Paulxp** [comment] 2022-03-06 12:26
Okay, just give me some time please. When the same situation occures with auto turn off dishwasher, i ll provide verbose log for you. Thanx

**Comment by Paulxp** [comment] 2022-03-13 17:15
Hi,
here my debug log. I turned on dishwasher manually at 18:07:25 and it was automatically powered off at 18:07:30


Line 47620: [13/03/2022, 18:07:25] [HomeConnect] [Umývačka riadu] Event NOTIFY (2 items)
	Line 47621: [13/03/2022, 18:07:25] [HomeConnect] [Umývačka riadu] BSH.Common.Root.SelectedProgram=Dishcare.Dishwasher.Program.Eco50 (1 listeners)
	Line 47622: [13/03/2022, 18:07:25] [HomeConnect] [Umývačka riadu] BSH.Common.Option.RemainingProgramTime=14100 seconds (1 listeners)
	Line 47623: [13/03/2022, 18:07:25] [HomeConnect] [Umývačka riadu] Cache 'Appliance program select Dishcare.Dishwasher.Program.Eco50' [en-GB, updated 106251 seconds ago] is too old
	Line 47624: [13/03/2022, 18:07:25] [HomeConnect] [Umývačka riadu] Switching appliance on to read program options
	Line 47625: [13/03/2022, 18:07:25] [HomeConnect] Home Connect request #199: PUT https://api.home-connect.com/api/homeappliances/010110518272000437/settings/BSH.Common.Setting.PowerState
	Line 47650: [13/03/2022, 18:07:26] [HomeConnect] [Umývačka riadu] Event NOTIFY (1 item)
	Line 47651: [13/03/2022, 18:07:26] [HomeConnect] [Umývačka riadu] BSH.Common.Setting.PowerState=BSH.Common.EnumType.PowerState.On (1 listeners)
	Line 47652: [13/03/2022, 18:07:26] [HomeConnect] [Umývačka riadu] Event STATUS (1 item)
	Line 47653: [13/03/2022, 18:07:26] [HomeConnect] [Umývačka riadu] BSH.Common.Status.OperationState=BSH.Common.EnumType.OperationState.Ready (12 listeners)
	Line 47654: [13/03/2022, 18:07:26] [HomeConnect] [Umývačka riadu] On
	Line 47655: [13/03/2022, 18:07:26] [HomeConnect] [Umývačka riadu] Inactive (Ready)
	Line 47656: [13/03/2022, 18:07:26] [HomeConnect] [Umývačka riadu] Event STATUS (1 item)
	Line 47657: [13/03/2022, 18:07:26] [HomeConnect] [Umývačka riadu] BSH.Common.Status.DoorState=BSH.Common.EnumType.DoorState.Open (1 listeners)
	Line 47658: [13/03/2022, 18:07:26] [HomeConnect] [Umývačka riadu] Door open
	Line 47659: [13/03/2022, 18:07:26] [HomeConnect] Home Connect request #199: OK +1230ms 
	Line 47660: [13/03/2022, 18:07:26] [HomeConnect] [Umývačka riadu] BSH.Common.Setting.PowerState=BSH.Common.EnumType.PowerState.On (1 listeners)
	Line 47661: [13/03/2022, 18:07:26] [HomeConnect] [Umývačka riadu] On
	Line 47710: [13/03/2022, 18:07:28] [HomeConnect] Home Connect request #200: GET https://api.home-connect.com/api/homeappliances/010110518272000437/programs/available/Dishcare.Dishwasher.Program.Eco50
	Line 47711: [13/03/2022, 18:07:29] [HomeConnect] Home Connect request #200: OK +173ms 
	Line 47712: [13/03/2022, 18:07:29] [HomeConnect] [Umývačka riadu] 'Appliance program select Dishcare.Dishwasher.Program.Eco50' written to cache
	Line 47713: [13/03/2022, 18:07:29] [HomeConnect] [Umývačka riadu] Cache saved (16 entries)
	Line 47714: [13/03/2022, 18:07:29] [HomeConnect] Home Connect request #201: PUT https://api.home-connect.com/api/homeappliances/010110518272000437/settings/BSH.Common.Setting.PowerState
	Line 47739: [13/03/2022, 18:07:30] [HomeConnect] [Umývačka riadu] Event NOTIFY (1 item)
	Line 47740: [13/03/2022, 18:07:30] [HomeConnect] [Umývačka riadu] BSH.Common.Setting.PowerState=BSH.Common.EnumType.PowerState.Off (1 listeners)
	Line 47741: [13/03/2022, 18:07:30] [HomeConnect] Home Connect request #201: OK +1188ms 
	Line 47742: [13/03/2022, 18:07:30] [HomeConnect] [Umývačka riadu] BSH.Common.Setting.PowerState=BSH.Common.EnumType.PowerState.Off (1 listeners)
	Line 47743: [13/03/2022, 18:07:30] [HomeConnect] Scheduling configuration schema write
	Line 47744: [13/03/2022, 18:07:30] [HomeConnect] [Umývačka riadu] 'Program details' written to cache
	Line 47745: [13/03/2022, 18:07:30] [HomeConnect] [Umývačka riadu] Off
	Line 47746: [13/03/2022, 18:07:30] [HomeConnect] [Umývačka riadu] Cache saved (16 entries)
	Line 47747: [13/03/2022, 18:07:30] [HomeConnect] [Umývačka riadu] Event STATUS (1 item)
	Line 47748: [13/03/2022, 18:07:30] [HomeConnect] [Umývačka riadu] BSH.Common.Status.OperationState=BSH.Common.EnumType.OperationState.Inactive (12 listeners)
	Line 47749: [13/03/2022, 18:07:30] [HomeConnect] [Umývačka riadu] Inactive (Inactive)
	Line 47844: [13/03/2022, 18:07:33] [HomeConnect] Scheduled configuration schema write complete
	Line 47895: [13/03/2022, 18:07:36] [HomeConnect] [Umývačka riadu] Event NOTIFY (1 item)
	Line 47896: [13/03/2022, 18:07:36] [HomeConnect] [Umývačka riadu] BSH.Common.Setting.PowerState=BSH.Common.EnumType.PowerState.On (1 listeners)
	Line 47897: [13/03/2022, 18:07:36] [HomeConnect] [Umývačka riadu] On
	Line 47898: [13/03/2022, 18:07:36] [HomeConnect] [Umývačka riadu] Event STATUS (1 item)
	Line 47899: [13/03/2022, 18:07:36] [HomeConnect] [Umývačka riadu] BSH.Common.Status.OperationState=BSH.Common.EnumType.OperationState.Ready (12 listeners)
	Line 47900: [13/03/2022, 18:07:36] [HomeConnect] [Umývačka riadu] Inactive (Ready)
	Line 48094: [13/03/2022, 18:07:44] [HomeConnect] [Umývačka riadu] Event NOTIFY (2 items)
	Line 48095: [13/03/2022, 18:07:44] [HomeConnect] [Umývačka riadu] BSH.Common.Root.SelectedProgram=Dishcare.Dishwasher.Program.Kurz60 (1 listeners)
	Line 48096: [13/03/2022, 18:07:44] [HomeConnect] [Umývačka riadu] BSH.Common.Option.RemainingProgramTime=5340 seconds (1 listeners)
	Line 48097: [13/03/2022, 18:07:44] [HomeConnect] [Umývačka riadu] Cache 'Appliance program select Dishcare.Dishwasher.Program.Kurz60' [en-GB, updated 103277 seconds ago] is too old
	Line 48098: [13/03/2022, 18:07:44] [HomeConnect] Home Connect request #202: GET https://api.home-connect.com/api/homeappliances/010110518272000437/programs/available/Dishcare.Dishwasher.Program.Kurz60
	Line 48099: [13/03/2022, 18:07:44] [HomeConnect] Home Connect request #202: OK +195ms 
	Line 48100: [13/03/2022, 18:07:44] [HomeConnect] [Umývačka riadu] 'Appliance program select Dishcare.Dishwasher.Program.Kurz60' written to cache
	Line 48101: [13/03/2022, 18:07:44] [HomeConnect] [Umývačka riadu] Cache saved (16 entries)
	Line 48102: [13/03/2022, 18:07:44] [HomeConnect] Scheduling configuration schema write
	Line 48103: [13/03/2022, 18:07:44] [HomeConnect] [Umývačka riadu] 'Program details' written to cache
	Line 48104: [13/03/2022, 18:07:44] [HomeConnect] [Umývačka riadu] Cache saved (16 entries)
	Line 48199: [13/03/2022, 18:07:47] [HomeConnect] Configuration schema file updated: /var/lib/homebridge/.homebridge-homeconnect-v1.schema.json
	Line 48200: [13/03/2022, 18:07:47] [HomeConnect] Scheduled configuration schema write complete
	Line 48273: [13/03/2022, 18:07:50] [HomeConnect] [Umývačka riadu] Event NOTIFY (1 item)
	Line 48274: [13/03/2022, 18:07:50] [HomeConnect] [Umývačka riadu] BSH.Common.Root.ActiveProgram=Dishcare.Dishwasher.Program.Kurz60 (9 listeners)
	Line 48275: [13/03/2022, 18:07:50] [HomeConnect] [Umývačka riadu] Event STATUS (1 item)
	Line 48276: [13/03/2022, 18:07:50] [HomeConnect] [Umývačka riadu] BSH.Common.Status.OperationState=BSH.Common.EnumType.OperationState.Run (12 listeners)
	Line 48277: [13/03/2022, 18:07:50] [HomeConnect] [Umývačka riadu] Program 'Express 60' (Dishcare.Dishwasher.Program.Kurz60) active
	Line 48278: [13/03/2022, 18:07:50] [HomeConnect] [Umývačka riadu] Active (Run)
	Line 48279: [13/03/2022, 18:07:50] [HomeConnect] [Umývačka riadu] Program has 1 hour 29 minutes remaining
	Line 48282: [13/03/2022, 18:07:50] [HomeConnect] [Umývačka riadu] Event STATUS (1 item)
	Line 48283: [13/03/2022, 18:07:50] [HomeConnect] [Umývačka riadu] BSH.Common.Status.DoorState=BSH.Common.EnumType.DoorState.Closed (1 listeners)
	Line 48284: [13/03/2022, 18:07:50] [HomeConnect] [Umývačka riadu] Door closed
	Line 49917: [13/03/2022, 18:08:52] [HomeConnect] [Umývačka riadu] Event NOTIFY (1 item)
	Line 49918: [13/03/2022, 18:08:52] [HomeConnect] [Umývačka riadu] BSH.Common.Option.ProgramProgress=1 % (0 listeners)
	Line 49919: [13/03/2022, 18:08:52] [HomeConnect] [Umývačka riadu] Event NOTIFY (1 item)
	Line 49920: [13/03/2022, 18:08:52] [HomeConnect] [Umývačka riadu] BSH.Common.Option.RemainingProgramTime=5280 seconds (1 listeners)
	Line 49921: [13/03/2022, 18:08:52] [HomeConnect] [Umývačka riadu] Program has 1 hour 28 minutes remaining

**Comment by thoukydides** [comment] 2022-03-13 18:34
Thank you for that debug log. It is very helpful. 

It looks like the Home Connect API is reporting appliance state change events in a rather odd order when you turn it on the first time:
1. `BSH.Common.Root.SelectedProgram=Dishcare.Dishwasher.Program.Eco50` and `BSH.Common.Option.RemainingProgramTime=14100 seconds`
2. `BSH.Common.Setting.PowerState=BSH.Common.EnumType.PowerState.On`
3. `BSH.Common.Status.OperationState=BSH.Common.EnumType.OperationState.Ready`
4. `BSH.Common.Status.DoorState=BSH.Common.EnumType.DoorState.Open`

When the plugin receives event 1 it finds that its cached details for program `Eco50` are too old, so decides to refresh the program's options. As I explained previously, this requires the appliance to be switched on and idle. At this stage the plugin still thinks that the appliance is switched off (since the event for it being switched on won't arrive until event 2). Hence, the plugin switches the appliance on itself (PUT request 199).

Events 2, 3, and 4, then get delivered to the plugin. These are immediately followed by a success response for the command to switch the appliance on (i.e. the OK response to request 199).

The problem is that these are precisely the same events that would be received had the appliance been off, and it was the plugin's command that switched it on. There is no way for the plugin to distinguish between that and the appliance being switched on manually.  So, at this stage the plugin thinks that it was responsible for switching the power on.

The plugin proceeds to read the program's options (PUT request 200). It then attempts to restore the appliance's initial state by switching the power back off (PUT request 201).

The second time that you switched the appliance on the events were received in a more sensible order:
1. `BSH.Common.Setting.PowerState=BSH.Common.EnumType.PowerState.On `
2. `BSH.Common.Status.OperationState=BSH.Common.EnumType.OperationState.Ready`
3. `BSH.Common.Root.SelectedProgram=Dishcare.Dishwasher.Program.Kurz60` and `BSH.Common.Option.RemainingProgramTime=5340 seconds`

Because the plugin receives the power state event first it doesn't attempt to switch the appliance on/off itself around reading the program's options.

Most of the Home Connect appliances lock-out remote control when they are being operated  manually, as indicated by [`BSH.Common.Status.LocalControlActive`](https://api-docs.home-connect.com/states?#local-control-state).  This prevents this sort of issue because it gives time for events to be delivered before the plugin can try to control the appliance. However, for some reason this is not implemented for Dishwasher appliances.

I might be able to make a special case of this very specific scenario of the plugin updating details of a program when it is already selected. This particular case is only triggered when the Home Connect servers report a change to `BSH.Common.Root.SelectedProgram`, which probably only occurs when the appliance is already switched on (even if that state has not yet been indicated). This probably requires the combination of a short delay to allow all of the events to be received, followed by just trying to read the program options without attempting to set the power state or program explicitly.

I will have a think about it....

**Comment by thoukydides** [comment] 2022-03-14 08:51
v0.23.8 should hopefully fix this issue.

The plugin no longer attempts to control the appliance when reading the currently selected program's options. It will now only switch the appliance on/off or change the selected program to read the program options the first time that the plugin is used (or after its cache has been deleted), or when the HomeKit `Identify` mechanism is invoked.

Additionally, there is now a short delay between receiving the `BSH.Common.Root.SelectedProgram` event and checking whether the state is suitable for reading the program's options. This will give some opportunity for out-of-order events to arrive.

@Paulxp , please let me know whether this fixes the issue for you.

**Comment by thoukydides** [comment] 2022-04-01 16:42
In the absence of any new problem reports I assume that this issue has been fixed, so I am closing it.

**Closed by thoukydides** 2022-04-01 16:42 UTC
