### ISSUE TITLE
Not a HOOBS plugin / Dryer program configuration

### ISSUE THREAD

**Issue by asbesto01** [thoukydides/homebridge-homeconnect#67] opened 2021-12-26 17:35 UTC
#### Description of Issue
Apple Home app --> all devices stuck on **UPDATING**. When plugin is uninstalled, normal behavior

#### Plugin Version
0.23.3
Hoobs: 4.1.20
Node version: 16.13.1
Homebridge version: 1.3.8
Machine: raspberry pi4

#### Home Connect Appliance(s)

Bosch Washer (E-Nr: WAL28RH0IT/01)
Bosch Dryer (E-Nr: WTX87KH9IT/01)

#### HomeKit App(s)
Apple Home

#### Log File

getting warnings:

25/12/2021, 22:08:47HomeConnectHomeConnectWARNING[Asciugatrice] 1 of 8 programs are currently unavailable
25/12/2021, 22:08:47HomeConnectHomeConnectWARNING[Asciugatrice] Missing options for 1 programs
25/12/2021, 22:08:47HomeConnectHomeConnectWARNING[Asciugatrice] To update the program options for this appliance:
25/12/2021, 22:08:47HomeConnectHomeConnectWARNING[Asciugatrice]   - Enable remote control on the appliance
25/12/2021, 22:08:47HomeConnectHomeConnectWARNING[Asciugatrice]   - Avoid operating the appliance locally
25/12/2021, 22:08:47HomeConnectHomeConnectWARNING[Asciugatrice]   - Ensure that no program is active
25/12/2021, 22:08:47HomeConnectHomeConnectWARNING[Asciugatrice]   - Fill any consumables that may be required
25/12/2021, 22:08:47HomeConnectHomeConnectWARNING[Asciugatrice]   - Either restart Bridge or invoke the appliance's Identify routine

entire plugin log file:

25/12/2021, 21:36:45HomeConnectHomeConnectWARNING[Asciugatrice]   - Enable remote control on the appliance
25/12/2021, 21:36:45HomeConnectHomeConnectWARNING[Asciugatrice]   - Avoid operating the appliance locally
25/12/2021, 21:36:45HomeConnectHomeConnectWARNING[Asciugatrice]   - Ensure that no program is active
25/12/2021, 21:36:45HomeConnectHomeConnectWARNING[Asciugatrice]   - Fill any consumables that may be required
25/12/2021, 21:36:45HomeConnectHomeConnectWARNING[Asciugatrice]   - Either restart Bridge or invoke the appliance's Identify routine
25/12/2021, 21:36:45HomeConnectHomeConnect[Asciugatrice] Adding services for 8 programs
25/12/2021, 21:36:45HomeConnectHomeConnect[Asciugatrice]     'Cotton' (LaundryCare.Dryer.Program.Cotton)
25/12/2021, 21:36:45HomeConnectHomeConnect[Asciugatrice]     'Delicates' (LaundryCare.Dryer.Program.Delicates)
25/12/2021, 21:36:45HomeConnectHomeConnect[Asciugatrice]     'Hygiene' (LaundryCare.Dryer.Program.Hygiene)
25/12/2021, 21:36:45HomeConnectHomeConnect[Asciugatrice]     'Mixed Fabrics' (LaundryCare.Dryer.Program.Mix)
25/12/2021, 21:36:45HomeConnectHomeConnect[Asciugatrice]     'Outdoor' (LaundryCare.Dryer.Program.Outdoor)
25/12/2021, 21:36:45HomeConnectHomeConnect[Asciugatrice]     'Rapid 40' (LaundryCare.Dryer.Program.Super40)
25/12/2021, 21:36:45HomeConnectHomeConnect[Asciugatrice]     'Easy-Care' (LaundryCare.Dryer.Program.Synthetic)
25/12/2021, 21:36:45HomeConnectHomeConnect[Asciugatrice]     'Timed programme warm' (LaundryCare.Dryer.Program.TimeWarm)
25/12/2021, 21:36:45HomeConnectHomeConnect[Asciugatrice] Removing services for 0 programs
25/12/2021, 21:36:45HomeConnectHomeConnectWARNING[Lavatrice] Temporarily selecting program LaundryCare.Washer.Program.Sensitive to read its options
25/12/2021, 21:36:48HomeConnectHomeConnect[Lavatrice] Finished reading available program options
25/12/2021, 21:36:48HomeConnectHomeConnect[Lavatrice] Adding services for 9 programs
25/12/2021, 21:36:48HomeConnectHomeConnect[Lavatrice]     'Cotton' (LaundryCare.Washer.Program.Cotton)
25/12/2021, 21:36:48HomeConnectHomeConnect[Lavatrice]     'Easy-Care' (LaundryCare.Washer.Program.EasyCare)
25/12/2021, 21:36:48HomeConnectHomeConnect[Lavatrice]     'Mixed Load' (LaundryCare.Washer.Program.Mix)
25/12/2021, 21:36:48HomeConnectHomeConnect[Lavatrice]     'DelicatesSilk' (LaundryCare.Washer.Program.DelicatesSilk)
25/12/2021, 21:36:48HomeConnectHomeConnect[Lavatrice]     'Wool' (LaundryCare.Washer.Program.Wool)
25/12/2021, 21:36:48HomeConnectHomeConnect[Lavatrice]     'Sportswear' (LaundryCare.Washer.Program.SportFitness)
25/12/2021, 21:36:48HomeConnectHomeConnect[Lavatrice]     'ShirtsBlouses' (LaundryCare.Washer.Program.ShirtsBlouses)
25/12/2021, 21:36:48HomeConnectHomeConnect[Lavatrice]     'Dark Wash  Easy-Care Plus' (LaundryCare.Washer.Program.DarkWash)
25/12/2021, 21:36:48HomeConnectHomeConnect[Lavatrice]     'Allergy Plus' (LaundryCare.Washer.Program.Sensitive)
25/12/2021, 21:36:48HomeConnectHomeConnect[Lavatrice] Removing services for 0 programs
25/12/2021, 21:41:48HomeConnectHomeConnect[Lavatrice] Off
25/12/2021, 22:08:43HomeConnectHomeConnectnew HomeConnectPlatform
25/12/2021, 22:08:44HomeConnectHomeConnectRestored 2 cached accessories
25/12/2021, 22:08:44HomeConnectHomeConnectStarting events stream for all appliances
25/12/2021, 22:08:44HomeConnectHomeConnect[Lavatrice] Bosch Washer (E-Nr: WAL28RH0IT/01)
25/12/2021, 22:08:44HomeConnectHomeConnect[Asciugatrice] Bosch Dryer (E-Nr: WTX87KH9IT/01)
25/12/2021, 22:08:44HomeConnectHomeConnect[Lavatrice] Can be placed in standby
25/12/2021, 22:08:44HomeConnectHomeConnect[Asciugatrice] Cannot be switched off
25/12/2021, 22:08:45HomeConnectHomeConnect[Lavatrice] Door closed
25/12/2021, 22:08:45HomeConnectHomeConnect[Lavatrice] On
25/12/2021, 22:08:45HomeConnectHomeConnect[Lavatrice] Inactive (Ready)
25/12/2021, 22:08:45HomeConnectHomeConnect[Lavatrice] Remote operation enabled (remote control activated, remote start allowed)
25/12/2021, 22:08:45HomeConnectHomeConnect[Lavatrice] Child lock disabled
25/12/2021, 22:08:45HomeConnectHomeConnect[Lavatrice] On
25/12/2021, 22:08:46HomeConnectHomeConnect[Lavatrice] Connected
25/12/2021, 22:08:46HomeConnectHomeConnect[Lavatrice] Finished reading available program options
25/12/2021, 22:08:46HomeConnectHomeConnect[Lavatrice] Adding services for 9 programs
25/12/2021, 22:08:46HomeConnectHomeConnect[Lavatrice]     'Cotton' (LaundryCare.Washer.Program.Cotton)
25/12/2021, 22:08:46HomeConnectHomeConnect[Lavatrice]     'Easy-Care' (LaundryCare.Washer.Program.EasyCare)
25/12/2021, 22:08:46HomeConnectHomeConnect[Lavatrice]     'Mixed Load' (LaundryCare.Washer.Program.Mix)
25/12/2021, 22:08:46HomeConnectHomeConnect[Lavatrice]     'DelicatesSilk' (LaundryCare.Washer.Program.DelicatesSilk)
25/12/2021, 22:08:46HomeConnectHomeConnect[Lavatrice]     'Wool' (LaundryCare.Washer.Program.Wool)
25/12/2021, 22:08:46HomeConnectHomeConnect[Lavatrice]     'Sportswear' (LaundryCare.Washer.Program.SportFitness)
25/12/2021, 22:08:46HomeConnectHomeConnect[Lavatrice]     'ShirtsBlouses' (LaundryCare.Washer.Program.ShirtsBlouses)
25/12/2021, 22:08:46HomeConnectHomeConnect[Lavatrice]     'Dark Wash  Easy-Care Plus' (LaundryCare.Washer.Program.DarkWash)
25/12/2021, 22:08:46HomeConnectHomeConnect[Lavatrice]     'Allergy Plus' (LaundryCare.Washer.Program.Sensitive)
25/12/2021, 22:08:46HomeConnectHomeConnect[Lavatrice] Removing services for 0 programs
25/12/2021, 22:08:47HomeConnectHomeConnect[Asciugatrice] Door closed
25/12/2021, 22:08:47HomeConnectHomeConnect[Asciugatrice] On
25/12/2021, 22:08:47HomeConnectHomeConnect[Asciugatrice] Inactive (Ready)
25/12/2021, 22:08:47HomeConnectHomeConnect[Asciugatrice] Remote operation enabled (remote control activated, remote start allowed)
25/12/2021, 22:08:47HomeConnectHomeConnect[Asciugatrice] Child lock disabled
25/12/2021, 22:08:47HomeConnectHomeConnect[Asciugatrice] On
25/12/2021, 22:08:47HomeConnectHomeConnect[Asciugatrice] Connected
25/12/2021, 22:08:47HomeConnectHomeConnectWARNING[Asciugatrice] 1 of 8 programs are currently unavailable
25/12/2021, 22:08:47HomeConnectHomeConnectWARNING[Asciugatrice] Missing options for 1 programs
25/12/2021, 22:08:47HomeConnectHomeConnectWARNING[Asciugatrice] To update the program options for this appliance:
25/12/2021, 22:08:47HomeConnectHomeConnectWARNING[Asciugatrice]   - Enable remote control on the appliance
25/12/2021, 22:08:47HomeConnectHomeConnectWARNING[Asciugatrice]   - Avoid operating the appliance locally
25/12/2021, 22:08:47HomeConnectHomeConnectWARNING[Asciugatrice]   - Ensure that no program is active
25/12/2021, 22:08:47HomeConnectHomeConnectWARNING[Asciugatrice]   - Fill any consumables that may be required
25/12/2021, 22:08:47HomeConnectHomeConnectWARNING[Asciugatrice]   - Either restart Bridge or invoke the appliance's Identify routine
25/12/2021, 22:08:47HomeConnectHomeConnect[Asciugatrice] Adding services for 8 programs
25/12/2021, 22:08:47HomeConnectHomeConnect[Asciugatrice]     'Cotton' (LaundryCare.Dryer.Program.Cotton)
25/12/2021, 22:08:47HomeConnectHomeConnect[Asciugatrice]     'Delicates' (LaundryCare.Dryer.Program.Delicates)
25/12/2021, 22:08:47HomeConnectHomeConnect[Asciugatrice]     'Hygiene' (LaundryCare.Dryer.Program.Hygiene)
25/12/2021, 22:08:47HomeConnectHomeConnect[Asciugatrice]     'Mixed Fabrics' (LaundryCare.Dryer.Program.Mix)
25/12/2021, 22:08:47HomeConnectHomeConnect[Asciugatrice]     'Outdoor' (LaundryCare.Dryer.Program.Outdoor)
25/12/2021, 22:08:47HomeConnectHomeConnect[Asciugatrice]     'Rapid 40' (LaundryCare.Dryer.Program.Super40)
25/12/2021, 22:08:47HomeConnectHomeConnect[Asciugatrice]     'Easy-Care' (LaundryCare.Dryer.Program.Synthetic)
25/12/2021, 22:08:47HomeConnectHomeConnect[Asciugatrice]     'Timed programme warm' (LaundryCare.Dryer.Program.TimeWarm)
25/12/2021, 22:08:47HomeConnectHomeConnect[Asciugatrice] Removing services for 0 programs
25/12/2021, 22:10:33HomeConnectHomeConnect[Asciugatrice] Door open
25/12/2021, 22:10:33HomeConnectHomeConnect[Asciugatrice] Remote operation NOT enabled (remote control activated, remote start disallowed)
25/12/2021, 22:10:33HomeConnectHomeConnect[Asciugatrice] Door closed
25/12/2021, 22:10:36HomeConnectHomeConnect[Asciugatrice] Manual mode (remote control not activated, remote start disallowed, being operated locally)
25/12/2021, 22:10:36HomeConnectHomeConnect[Asciugatrice] Manual mode (remote control not activated, remote start allowed, being operated locally)
25/12/2021, 22:10:43HomeConnectHomeConnect[Asciugatrice] Remote operation enabled (remote control activated, remote start allowed)
25/12/2021, 22:10:44HomeConnectHomeConnect[Asciugatrice] Disconnected
25/12/2021, 22:11:03HomeConnectHomeConnect[Asciugatrice] Door closed
25/12/2021, 22:11:03HomeConnectHomeConnect[Asciugatrice] Inactive (Ready)
25/12/2021, 22:11:03HomeConnectHomeConnect[Asciugatrice] Remote operation enabled (remote control activated, remote start allowed)
25/12/2021, 22:11:03HomeConnectHomeConnect[Asciugatrice] Child lock disabled
25/12/2021, 22:11:03HomeConnectHomeConnect[Asciugatrice] On
25/12/2021, 22:11:03HomeConnectHomeConnect[Asciugatrice] Connected
25/12/2021, 22:12:14HomeConnectHomeConnectnew HomeConnectPlatform
25/12/2021, 22:12:14HomeConnectHomeConnectRestored 2 cached accessories
25/12/2021, 22:12:14HomeConnectHomeConnectStarting events stream for all appliances
25/12/2021, 22:12:14HomeConnectHomeConnect[Lavatrice] Bosch Washer (E-Nr: WAL28RH0IT/01)
25/12/2021, 22:12:14HomeConnectHomeConnect[Asciugatrice] Bosch Dryer (E-Nr: WTX87KH9IT/01)
25/12/2021, 22:12:14HomeConnectHomeConnect[Asciugatrice] Cannot be switched off
25/12/2021, 22:12:14HomeConnectHomeConnect[Lavatrice] Can be placed in standby
25/12/2021, 22:12:15HomeConnectHomeConnect[Lavatrice] Door closed
25/12/2021, 22:12:15HomeConnectHomeConnect[Lavatrice] On
25/12/2021, 22:12:15HomeConnectHomeConnect[Lavatrice] Inactive (Ready)
25/12/2021, 22:12:15HomeConnectHomeConnect[Lavatrice] Remote operation enabled (remote control activated, remote start allowed)
25/12/2021, 22:12:15HomeConnectHomeConnect[Asciugatrice] Door closed
25/12/2021, 22:12:15HomeConnectHomeConnect[Asciugatrice] On
25/12/2021, 22:12:15HomeConnectHomeConnect[Asciugatrice] Inactive (Ready)
25/12/2021, 22:12:15HomeConnectHomeConnect[Asciugatrice] Remote operation enabled (remote control activated, remote start allowed)
25/12/2021, 22:12:15HomeConnectHomeConnect[Asciugatrice] Child lock disabled
25/12/2021, 22:12:15HomeConnectHomeConnect[Asciugatrice] On
25/12/2021, 22:12:15HomeConnectHomeConnect[Lavatrice] Child lock disabled
25/12/2021, 22:12:15HomeConnectHomeConnect[Lavatrice] On
25/12/2021, 22:12:15HomeConnectHomeConnect[Lavatrice] Connected
25/12/2021, 22:12:15HomeConnectHomeConnect[Asciugatrice] Connected
25/12/2021, 22:12:16HomeConnectHomeConnectWARNING[Asciugatrice] 1 of 8 programs are currently unavailable
25/12/2021, 22:12:16HomeConnectHomeConnect[Lavatrice] Finished reading available program options
25/12/2021, 22:12:16HomeConnectHomeConnect[Lavatrice] Adding services for 9 programs
25/12/2021, 22:12:16HomeConnectHomeConnect[Lavatrice]     'Cotton' (LaundryCare.Washer.Program.Cotton)
25/12/2021, 22:12:16HomeConnectHomeConnect[Lavatrice]     'Easy-Care' (LaundryCare.Washer.Program.EasyCare)
25/12/2021, 22:12:16HomeConnectHomeConnect[Lavatrice]     'Mixed Load' (LaundryCare.Washer.Program.Mix)
25/12/2021, 22:12:16HomeConnectHomeConnect[Lavatrice]     'DelicatesSilk' (LaundryCare.Washer.Program.DelicatesSilk)
25/12/2021, 22:12:16HomeConnectHomeConnect[Lavatrice]     'Wool' (LaundryCare.Washer.Program.Wool)
25/12/2021, 22:12:16HomeConnectHomeConnect[Lavatrice]     'Sportswear' (LaundryCare.Washer.Program.SportFitness)
25/12/2021, 22:12:16HomeConnectHomeConnect[Lavatrice]     'ShirtsBlouses' (LaundryCare.Washer.Program.ShirtsBlouses)
25/12/2021, 22:12:16HomeConnectHomeConnect[Lavatrice]     'Dark Wash  Easy-Care Plus' (LaundryCare.Washer.Program.DarkWash)
25/12/2021, 22:12:16HomeConnectHomeConnect[Lavatrice]     'Allergy Plus' (LaundryCare.Washer.Program.Sensitive)
25/12/2021, 22:12:16HomeConnectHomeConnect[Lavatrice] Removing services for 0 programs
25/12/2021, 22:12:16HomeConnectHomeConnectWARNING[Asciugatrice] Missing options for 1 programs
25/12/2021, 22:12:16HomeConnectHomeConnectWARNING[Asciugatrice] To update the program options for this appliance:
25/12/2021, 22:12:16HomeConnectHomeConnectWARNING[Asciugatrice]   - Enable remote control on the appliance
25/12/2021, 22:12:16HomeConnectHomeConnectWARNING[Asciugatrice]   - Avoid operating the appliance locally
25/12/2021, 22:12:16HomeConnectHomeConnectWARNING[Asciugatrice]   - Ensure that no program is active
25/12/2021, 22:12:16HomeConnectHomeConnectWARNING[Asciugatrice]   - Fill any consumables that may be required
25/12/2021, 22:12:16HomeConnectHomeConnectWARNING[Asciugatrice]   - Either restart Bridge or invoke the appliance's Identify routine
25/12/2021, 22:12:16HomeConnectHomeConnect[Asciugatrice] Adding services for 8 programs
25/12/2021, 22:12:16HomeConnectHomeConnect[Asciugatrice]     'Cotton' (LaundryCare.Dryer.Program.Cotton)
25/12/2021, 22:12:16HomeConnectHomeConnect[Asciugatrice]     'Delicates' (LaundryCare.Dryer.Program.Delicates)
25/12/2021, 22:12:16HomeConnectHomeConnect[Asciugatrice]     'Hygiene' (LaundryCare.Dryer.Program.Hygiene)
25/12/2021, 22:12:16HomeConnectHomeConnect[Asciugatrice]     'Mixed Fabrics' (LaundryCare.Dryer.Program.Mix)
25/12/2021, 22:12:16HomeConnectHomeConnect[Asciugatrice]     'Outdoor' (LaundryCare.Dryer.Program.Outdoor)
25/12/2021, 22:12:16HomeConnectHomeConnect[Asciugatrice]     'Rapid 40' (LaundryCare.Dryer.Program.Super40)
25/12/2021, 22:12:16HomeConnectHomeConnect[Asciugatrice]     'Easy-Care' (LaundryCare.Dryer.Program.Synthetic)
25/12/2021, 22:12:16HomeConnectHomeConnect[Asciugatrice]     'Timed programme warm' (LaundryCare.Dryer.Program.TimeWarm)
25/12/2021, 22:12:16HomeConnectHomeConnect[Asciugatrice] Removing services for 0 programs
25/12/2021, 22:16:26HomeConnectHomeConnect[Lavatrice] Off
25/12/2021, 22:22:31HomeConnectHomeConnect[Lavatrice] On
25/12/2021, 22:27:32HomeConnectHomeConnect[Lavatrice] Off
26/12/2021, 02:05:39HomeConnectHomeConnect[Asciugatrice] Disconnected
26/12/2021, 02:12:48HomeConnectHomeConnect[Asciugatrice] Door closed
26/12/2021, 02:12:48HomeConnectHomeConnect[Asciugatrice] Inactive (Ready)
26/12/2021, 02:12:48HomeConnectHomeConnect[Asciugatrice] Remote operation enabled (remote control activated, remote start allowed)
26/12/2021, 02:12:48HomeConnectHomeConnect[Asciugatrice] Child lock disabled
26/12/2021, 02:12:48HomeConnectHomeConnect[Asciugatrice] On
26/12/2021, 02:12:48HomeConnectHomeConnect[Asciugatrice] Connected
26/12/2021, 11:42:42HomeConnectHomeConnect[Lavatrice] On
26/12/2021, 11:42:42HomeConnectHomeConnect[Lavatrice] Door open
26/12/2021, 11:42:42HomeConnectHomeConnect[Lavatrice] Manual mode (remote control not activated, remote start allowed, being operated locally)
26/12/2021, 11:42:44HomeConnectHomeConnect[Lavatrice] Door closed
26/12/2021, 11:42:50HomeConnectHomeConnect[Lavatrice] Remote operation enabled (remote control activated, remote start allowed)
26/12/2021, 11:47:46HomeConnectHomeConnect[Lavatrice] Off
26/12/2021, 12:48:45HomeConnectHomeConnectERRORTerminated events stream for all appliances: ESOCKETTIMEDOUT
26/12/2021, 12:48:45HomeConnectHomeConnectStarting events stream for all appliances
26/12/2021, 12:48:45HomeConnectHomeConnect[Lavatrice] Disconnected
26/12/2021, 12:48:45HomeConnectHomeConnect[Asciugatrice] Disconnected
26/12/2021, 12:48:47HomeConnectHomeConnect[Lavatrice] Door closed
26/12/2021, 12:48:47HomeConnectHomeConnect[Lavatrice] On
26/12/2021, 12:48:47HomeConnectHomeConnect[Lavatrice] Inactive (Ready)
26/12/2021, 12:48:47HomeConnectHomeConnect[Lavatrice] Remote operation enabled (remote control activated, remote start allowed)
26/12/2021, 12:48:47HomeConnectHomeConnect[Lavatrice] Child lock disabled
26/12/2021, 12:48:47HomeConnectHomeConnect[Lavatrice] On
26/12/2021, 12:48:47HomeConnectHomeConnect[Lavatrice] Connected
26/12/2021, 12:48:48HomeConnectHomeConnect[Asciugatrice] Door closed
26/12/2021, 12:48:48HomeConnectHomeConnect[Asciugatrice] Inactive (Ready)
26/12/2021, 12:48:48HomeConnectHomeConnect[Asciugatrice] Remote operation enabled (remote control activated, remote start allowed)
26/12/2021, 12:48:48HomeConnectHomeConnect[Asciugatrice] Child lock disabled
26/12/2021, 12:48:48HomeConnectHomeConnect[Asciugatrice] On
26/12/2021, 12:48:48HomeConnectHomeConnect[Asciugatrice] Connected
26/12/2021, 12:53:47HomeConnectHomeConnect[Lavatrice] Off

**Comment by thoukydides** [comment] 2021-12-26 18:49
Nothing in the log file would explain the UPDATING behaviour that you mention. That will be due to a communication issue between your iOS device and the Homebridge instance, and you have not provided any of the non-plugin Homebridge logs.

I see that you are using HOOBS. However, this is a Homebridge plugin. It is not a HOOBS plugin. The last time I tested it, this plugin worked under HOOBS, except for the graphical configuration editor (requiring the `config.json` file to be edited by hand). However, I would not be surprised if other incompatibilities have been introduced.

If you can provide a full log, ideally with HomeKit Accessory Protocol (HAP) logging enabled (which with Homebridge is achieved by setting the `DEBUG=*` environment variable), then I can take a look to see whether it is something obvious. Otherwise, I suggest you report the issue to the HOOBS developers; I consider it to be their responsibility to resolve any compatibility issues that they have introduced by forking their code from Homebridge.

The warnings that you highlight only affect the ability to configure additional options for one of your dryer's programs. I would be interested in seeing a log with debug enabled (which with Homebridge is done by adding the `-D` command line switch, but I have no idea how it is done with HOOBS) to see whether that reveals why there are problems reading the options for that program. However, this issue will not affect any other functionality, and will not be the cause of the UPDATING status.

**Comment by thoukydides** [comment] 2021-12-29 10:17
Updating my main installation to Node v16.13.1 LTS and homebridge v1.3.9 does not reveal any issues. Hence, I suspect that this is a HOOBS issue.

I just tried installing HOOBS on my Raspberry Pi... only to discover that HOOBS no longer supports anything older than model 3, and I only have a Model B available. Hence, I cannot currently test compatibility myself.

**Comment by thoukydides** [comment] 2021-12-29 13:56
There does not appear to be any stock available to buy of Raspberry Pi Models 4/3B/3B+... but I have finally managed to get HOOBS 4.1.20 running under a Ubuntu virtual machine.

Installing this plugin in that setup works fine for me. All of the appliances operate as expected from the Apple Home app. No tiles are marked as UPDATING.

The only problem is the one that I was already aware of, which is that HOOBS does not support hombridge-ui-x configuration schemas, so it is not possible to configure this plugin via the GUI. Instead, it is necessary to edit the config.json file by hand. I reported that issue to the HOOBS developers a long time ago, but they don't seem interested in fixing it.

Anyway, unless you can provide a log file illustrating the problem there is nothing that I can do about it...

**Comment by asbesto01** [comment] 2022-01-20 10:09
Hello,

thank you for the multiple checks; I have managed to install the plugin in Homebridge and everything works perfectly, while in HOOBS issues are still persisting.

For this reason I moved my setup to Homebridge and fixed the issue.

Now I have another issue (I hope it's the final one!)

My dryer (Bosch WTX87KH9IT) has an ironing reduction function. this means that at the end of the cycle it performs 60 minutes (or 120 minutes) random movements to avoid clothes to fold.

I want to avoid this behavior, so how should I modify the following string?

"BOSCH-WAL28RH0IT-68A40E58D131": {
        "addprograms": "custom",
        "programs": [
            {
                "name": "Mix",
                "key": "LaundryCare.Washer.Program.Mix",
                "selectonly": false,
                "options": {
                    "LaundryCare.Washer.Option.SpinSpeed": "LaundryCare.Washer.EnumType.SpinSpeed.RPM1400",
                    "LaundryCare.Washer.Option.Temperature": "LaundryCare.Washer.EnumType.Temperature.GC20"
                }


This setting can be disabled in Home Connect:
![IMG_5963](https://user-images.githubusercontent.com/48592932/150318178-bdccacee-4f3a-4aa8-9e13-8616a1699de7.PNG)


![IMG_5964](https://user-images.githubusercontent.com/48592932/150318220-e5837f92-6e82-42db-a30c-a4c57bba977c.PNG)




 however I need the proper string to be inserted within Homebridge.

Thanks!

**Comment by thoukydides** [comment] 2022-01-20 10:26
Ironing reduction does not appear to be an option supported via the public API. According to https://api-docs.home-connect.com/programs-and-options the only available option is `LaundryCare.Dryer.Option.DryingTarget` which can be set to one of the following values:
* `LaundryCare.Dryer.EnumType.DryingTarget.IronDry` - The dryer will stop drying if the clothes are iron dry.
* `LaundryCare.Dryer.EnumType.DryingTarget.CupboardDry` - The dryer will stop drying if the clothes are cupboard dry.
* `LaundryCare.Dryer.EnumType.DryingTarget.CupboardDryPlus` - The dryer will stop drying if the clothes are absolutely dry.

However, the documentation is not always correct. Sometimes there are undocumented options.

You can check which options are supported by your specific appliance using the methods described on the [Wiki](https://github.com/thoukydides/homebridge-homeconnect/wiki/Programs):
* Use [homebridge-config-ui-x ](https://github.com/oznu/homebridge-config-ui-x) to edit the configuration.
* Use HomeKit's `Identify` routine for the appliance and look for the description in the plugin's log file.

I do not have a Dryer (or WasherDryer) that supports Home Connect, so cannot try this myself. Even if I did, the available options vary between models, and sometimes even between software versions.

The official Home Connect app does not use the public API, and sometimes supports extra functionality that is not available to this plugin. The fact that you can select this particular option in the app does not mean that it can be set by third-party software using the public API.

**Comment by asbesto01** [comment] 2022-01-20 10:37
Thanks for your reply!

Use homebridge-config-ui-x is not exposing anything relevant.

How to do this?

Use HomeKit's Identify routine for the appliance and look for the description in the plugin's log file.


Thanks

**Comment by thoukydides** [comment] 2022-01-20 10:48
If homebridge-config-ui-x does not show the option that you are looking for then it is not supported by the API.

The `Identify` routine requires use of a third-party HomeKit app. For example, in Eve it is invoked using by tapping one of the appliance's controls, on the next screen expanding the arrow next to the appliance's name (which initially says "updated just now" before fading), and then clicking "ID".

The other approach that you can use is to look at the `.homebridge/.homebridge-homeconnect-v1.schema.json` file (in the same directory as the `config.json`). That's where the plugin writes the configuration options that homebridge-config-ui-x presents in its configuration editor.

**Comment by asbesto01** [comment] 2022-01-20 11:00
Ok thank you, I have managed to do the identify routine in EVE where do I find the log file after I clicked ID?

**Comment by thoukydides** [comment] 2022-01-20 11:30
The log file is the same one where you found the authorisation URL during the initial plugin setup.

The location of the log file will depend on how you start homebridge, e.g. if you use systemd then it is viewed using journalctl, or if you launch homebridge interactively then it will be written to the console.

**Comment by asbesto01** [comment] 2022-01-20 11:34
amazing!

I managed to extract the full array of programs:

"BOSCH-WTX87KH9IT-68A40E2FAEB3": {
        "programs": [
            {
                "name": "Cotone",
                "key": "LaundryCare.Dryer.Program.Cotton",
                "options": {
                    "BSH.Common.Option.FinishInRelative": 0,
                    "_BSH.Common.Option.FinishInRelative": "Int [0 .. 86400] step 60 seconds OR Time HH:MM",
                    "LaundryCare.Dryer.Option.DryingTarget": "LaundryCare.Dryer.EnumType.DryingTarget.CupboardDry",
                    "_LaundryCare.Dryer.Option.DryingTarget": [
                        "LaundryCare.Dryer.EnumType.DryingTarget.IronDry",
                        "LaundryCare.Dryer.EnumType.DryingTarget.GentleDry",
                        "LaundryCare.Dryer.EnumType.DryingTarget.CupboardDry",
                        "LaundryCare.Dryer.EnumType.DryingTarget.CupboardDryPlus"
                    ]
                }
            },
            {
                "name": "Delicati",
                "key": "LaundryCare.Dryer.Program.Delicates",
                "options": {
                    "BSH.Common.Option.FinishInRelative": 0,
                    "_BSH.Common.Option.FinishInRelative": "Int [0 .. 86400] step 60 seconds OR Time HH:MM",
                    "LaundryCare.Dryer.Option.DryingTarget": "LaundryCare.Dryer.EnumType.DryingTarget.CupboardDry",
                    "_LaundryCare.Dryer.Option.DryingTarget": [
                        "LaundryCare.Dryer.EnumType.DryingTarget.IronDry",
                        "LaundryCare.Dryer.EnumType.DryingTarget.GentleDry",
                        "LaundryCare.Dryer.EnumType.DryingTarget.CupboardDry"
                    ]
                }
            },
            {
                "name": "Allergy Plus",
                "key": "LaundryCare.Dryer.Program.Hygiene",
                "options": {
                    "BSH.Common.Option.FinishInRelative": 0,
                    "_BSH.Common.Option.FinishInRelative": "Int [0 .. 86400] step 60 seconds OR Time HH:MM"
                }
            },
            {
                "name": "Mix",
                "key": "LaundryCare.Dryer.Program.Mix",
                "options": {
                    "BSH.Common.Option.FinishInRelative": 0,
                    "_BSH.Common.Option.FinishInRelative": "Int [0 .. 86400] step 60 seconds OR Time HH:MM",
                    "LaundryCare.Dryer.Option.DryingTarget": "LaundryCare.Dryer.EnumType.DryingTarget.CupboardDry",
                    "_LaundryCare.Dryer.Option.DryingTarget": [
                        "LaundryCare.Dryer.EnumType.DryingTarget.IronDry",
                        "LaundryCare.Dryer.EnumType.DryingTarget.GentleDry",
                        "LaundryCare.Dryer.EnumType.DryingTarget.CupboardDry",
                        "LaundryCare.Dryer.EnumType.DryingTarget.CupboardDryPlus"
                    ]
                }
            },
            {
                "name": "SportFitness",
                "key": "LaundryCare.Dryer.Program.Outdoor"
            },
            {
                "name": "Rapido 40 min",
                "key": "LaundryCare.Dryer.Program.Super40",
                "options": {
                    "BSH.Common.Option.FinishInRelative": 0,
                    "_BSH.Common.Option.FinishInRelative": "Int [0 .. 86400] step 60 seconds OR Time HH:MM"
                }
            },
            {
                "name": "Sintetici",
                "key": "LaundryCare.Dryer.Program.Synthetic",
                "options": {
                    "BSH.Common.Option.FinishInRelative": 0,
                    "_BSH.Common.Option.FinishInRelative": "Int [0 .. 86400] step 60 seconds OR Time HH:MM",
                    "LaundryCare.Dryer.Option.DryingTarget": "LaundryCare.Dryer.EnumType.DryingTarget.CupboardDry",
                    "_LaundryCare.Dryer.Option.DryingTarget": [
                        "LaundryCare.Dryer.EnumType.DryingTarget.IronDry",
                        "LaundryCare.Dryer.EnumType.DryingTarget.GentleDry",
                        "LaundryCare.Dryer.EnumType.DryingTarget.CupboardDry",
                        "LaundryCare.Dryer.EnumType.DryingTarget.CupboardDryPlus"
                    ]
                }
            },
            {
                "name": "Programma a tempo caldo",
                "key": "LaundryCare.Dryer.Program.TimeWarm",
                "options": {
                    "BSH.Common.Option.Duration": 1200,
                    "_BSH.Common.Option.Duration": "Int [1200 .. 12600] step 600 seconds"
                }
            }
        ]
    }





seems the option I needed is not exposed, and can only be managed manually or via Home Connect!

**Comment by thoukydides** [comment] 2022-01-20 11:53
> seems the option I needed is not exposed, and can only be managed manually or via Home Connect!

I suspected that would be the case.

The only thing that I can suggest is that you use https://developer.home-connect.com/support/contact to suggest an API enhancement, adding support for that option...

**Closed by thoukydides** 2022-01-20 11:53 UTC
