### ISSUE TITLE
Coffee Maker: Missing Programm options

### ISSUE THREAD

**Issue by Nils89** [thoukydides/homebridge-homeconnect#76] opened 2022-02-23 20:13 UTC
Some Programs like "Latte Macchiato" do not have any options. 
At the home connect app itself it has the options. 

And on one day I had the options also with this mode. But they are gone with a coffee maker restart. 

I have manuell added the options to the config.json and they are working 

I use the latest version.

**Comment by thoukydides** [comment] 2022-02-24 04:11
Sorry, it is not clear to me from your description what, if anything, you think the problem is.

If the problem is that some expected program options caanot be set then:

* It is common for the public Home Connect API to not offer some or all of the programs or options that the appliances do. This is seems to be especially the case for CoffeeMaker appliances… or maybe it is just that the owners of those appliances are more likely to want to set program options.
* It is also common for the public Home Connect app to support functionality that is not supported via the public Home Connect API.

... and in which case the new functionality would need to be added by the Home Connect team.

If it is that the options for the programs work but some programs do not have any options presented within the homebridge-config-ui-x graphical settings editor then:

* The plugin attempts to read and cache the supported programs and options when the homebridge first starts (and there are either no cached values or they are too old). This requires the plugin to switch-on the appliance and select each program in turn since that is the only reliable way to retrieve the information via the Home Connect API. However, this may not be possible depending on the state of the appliance at that time, e.g. if it is unplugged, being controlled locally, or consumables are low/missing. In these cases the problem will be recorded in the log file.
* This is a homebridge plugin, not a HOOBS plugin. HOOBS is not compatible with homebridge and its graphical configuration editor does not operate correctly with this plugin. If you are using HOOBS then you should report the issue to its developers, not here.

... and again in these cases there is unlikely to be anything that can/will be improved.

If you still think that there is a problem with this plugin then:

1. Write a much clearer description, including all of the information requested by the issue template.
2. Provide a full debug log file for homebridge being (re)started an a period of a few minutes afterwards. This should be captured with the `-D` option on the homebridge command line.
3. Provide a full debug log file for homebridge around a Homebridge `Identify` operation. This can be triggered with a third-party HomeKit app such as Elgato's Eve.
4. Provide a copy of your `.homebridge-homeconnect/.homebridge-homeconnect-v1.schema.json` file.

**Comment by thoukydides** [comment] 2022-03-13 08:26
It has been a few weeks without any clarification or further information being provided, so I am closing this issue.

**Closed** 2022-03-13 08:26 UTC
Labels: bug
