### ISSUE TITLE
Ice maker toggle for fridge

### ISSUE THREAD

**Issue by player1024** [thoukydides/homebridge-homeconnect#141] opened 2023-04-19 20:38 UTC
### Description of Enhancement

It looks like ice make on/off for fridge is a button on home connect app. Can this be “homebridged” over?

thanks!

### Home Connect Mapping

Setting or state (not sure)

### HomeKit Mapping

State

### Home Connect Appliance(s)

Thermador fridge freezer t36ft820ns/01

**Comment by thoukydides** [comment] 2023-04-20 04:32
Duplicate of #94 

The Home Connect API does not expose any ice maker functionality, so this cannot be implemented.

**Comment by thoukydides** [comment] 2023-04-20 05:31
Checking again, it looks like a new feature was added to the API about a week ago...
https://api-docs.home-connect.com/settings?#dispenser-enabled

**Comment by thoukydides** [comment] 2023-04-20 06:36
This should now be supported in v0.29.0.

Please note that a significant portion of the plugin has been rewritten in this release, so it is quite likely that some other functionality has been inadvertently changed or broken. If you encounter other problems then please raise a new issue.

**Closed by thoukydides** 2023-04-20 06:36 UTC
Labels: enhancement
