### ISSUE TITLE
Plugin does not support HOOBS / Node 16 (duplicate)

### ISSUE THREAD

**Issue by Gillennium-O** [thoukydides/homebridge-homeconnect#256] opened 2024-02-27 23:51 UTC
### Description of Issue

Hoobs HomeConnect stopped working for a while, and initial thoughts were that the latest plugin was checking for Hoobs version 5. But i'm running Hoobs on raspberry pi;  If I run the latest version I get errors as shown in "Steps to Reproduce", if I revert to an earlier version, I chose November 2023 randomly, the plugin works, 0.30.2 works fine.

### Expected Behaviour

The plugin should list all my appliances, and subsequently Hoobs should be able to control them via Apple HomeKit

### Steps to Reproduce

Restarting the bridge reproduces the error:

27/02/2024, 23:41:12homeconnectbridge stopping
27/02/2024, 23:41:17Homeconnect Bridge starting
27/02/2024, 23:41:20Homeconnect BridgeERRORError loading plugin "homebridge-homeconnect"
27/02/2024, 23:41:20Homeconnect BridgeERRORReadableStream is not defined
27/02/2024, 23:41:20Homeconnect BridgeERRORReferenceError: ReadableStream is not defined
    at Object.<anonymous> (/var/lib/hoobs/homeconnectbridge/node_modules/undici/lib/fetch/response.js:507:3)
    at Module._compile (node:internal/modules/cjs/loader:1198:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
    at Module.load (node:internal/modules/cjs/loader:1076:32)
    at Function.Module._load (node:internal/modules/cjs/loader:911:12)
    at Module.require (node:internal/modules/cjs/loader:1100:19)
    at require (node:internal/modules/cjs/helpers:119:18)
    at Object.<anonymous> (/var/lib/hoobs/homeconnectbridge/node_modules/undici/lib/fetch/index.js:11:5)
    at Module._compile (node:internal/modules/cjs/loader:1198:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
    at Module.load (node:internal/modules/cjs/loader:1076:32)
    at Function.Module._load (node:internal/modules/cjs/loader:911:12)
    at Module.require (node:internal/modules/cjs/loader:1100:19)
    at require (node:internal/modules/cjs/helpers:119:18)
    at Object.<anonymous> (/var/lib/hoobs/homeconnectbridge/node_modules/undici/index.js:97:19)
    at Module._compile (node:internal/modules/cjs/loader:1198:14)
27/02/2024, 23:41:20Homeconnect BridgeWARNINGNo plugins installed.
27/02/2024, 23:41:20Homeconnect BridgeLoading 1 platforms...
27/02/2024, 23:41:20Homeconnect BridgeBridge is running on port 51906

### Plugin Version

0.41.0

### Environment

- OS: 4.3.1
- Node: 16.20.2
- Homebridge: 1.7.0

### Diagnostic Checks

- [X] Home Connect app is able to control the appliance with Wi-Fi disabled.
- [X] Home Connect app shows three green lines in the Network section of the appliance Settings.
- [X] Unofficial [Home Connect Server Status](https://homeconnect.thouky.co.uk) shows servers up and no recent errors.
- [ ] Searched for [previously reported issues](https://github.com/thoukydides/homebridge-homeconnect/issues?q=is%3Aissue) and no similar ones found.
- [ ] Checked the [Home Connect API errors](https://api-docs.home-connect.com/general?#api-errors) and [authorisation errors](https://api-docs.home-connect.com/authorization?#authorization-errors) documentation.

### Log File

```shell
27/02/2024, 23:41:12homeconnectbridge stopping
27/02/2024, 23:41:17Homeconnect Bridge starting
27/02/2024, 23:41:20Homeconnect BridgeERRORError loading plugin "homebridge-homeconnect"
27/02/2024, 23:41:20Homeconnect BridgeERRORReadableStream is not defined
27/02/2024, 23:41:20Homeconnect BridgeERRORReferenceError: ReadableStream is not defined
    at Object.<anonymous> (/var/lib/hoobs/homeconnectbridge/node_modules/undici/lib/fetch/response.js:507:3)
    at Module._compile (node:internal/modules/cjs/loader:1198:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
    at Module.load (node:internal/modules/cjs/loader:1076:32)
    at Function.Module._load (node:internal/modules/cjs/loader:911:12)
    at Module.require (node:internal/modules/cjs/loader:1100:19)
    at require (node:internal/modules/cjs/helpers:119:18)
    at Object.<anonymous> (/var/lib/hoobs/homeconnectbridge/node_modules/undici/lib/fetch/index.js:11:5)
    at Module._compile (node:internal/modules/cjs/loader:1198:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
    at Module.load (node:internal/modules/cjs/loader:1076:32)
    at Function.Module._load (node:internal/modules/cjs/loader:911:12)
    at Module.require (node:internal/modules/cjs/loader:1100:19)
    at require (node:internal/modules/cjs/helpers:119:18)
    at Object.<anonymous> (/var/lib/hoobs/homeconnectbridge/node_modules/undici/index.js:97:19)
    at Module._compile (node:internal/modules/cjs/loader:1198:14)
27/02/2024, 23:41:20Homeconnect BridgeWARNINGNo plugins installed.
27/02/2024, 23:41:20Homeconnect BridgeLoading 1 platforms...
27/02/2024, 23:41:20Homeconnect BridgeBridge is running on port 51906
```

### Configuration

```json
I don't think it is the .json file as the config works in version 0.30.2

{
    "platform": "HomeConnect",
    "clientid": "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
    "clientSecret": "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
    "simulator": false
}
```

**Comment by Gillennium-O** [comment] 2024-02-28 00:04
After uninstalling the latest version 0.41.0, and installing 0.30.2 I get the following: 
28/02/2024, 00:00:25Homeconnect BridgeConfiguration change
28/02/2024, 00:00:25homeconnectbridge stopping
28/02/2024, 00:00:30Homeconnect Bridge starting
28/02/2024, 00:00:33Homeconnect BridgeLoaded plugin 'homebridge-homeconnect'
28/02/2024, 00:00:33Homeconnect BridgeLoading 1 platforms...
28/02/2024, 00:00:33Homeconnect BridgeHomeConnectnew HomeConnectPlatform
28/02/2024, 00:00:33Homeconnect BridgeHomeConnecthomebridge-homeconnect version 0.30.2
28/02/2024, 00:00:33Homeconnect BridgeHomeConnectBridge version 1.7.0 (satisfies >=1.4.0)
28/02/2024, 00:00:33Homeconnect BridgeHomeConnectBridge API version 2.7 (satisfies ^2.7)
28/02/2024, 00:00:33Homeconnect BridgeHomeConnectBridge HAP version 0.11.1 (satisfies >=0.9.0)
28/02/2024, 00:00:33Homeconnect BridgeBridge is running on port 51906.
28/02/2024, 00:00:33Homeconnect BridgeHomeConnectAttempting authorisation
...
28/02/2024, 00:01:15Homeconnect BridgeHomeConnectSuccessfully authorised
28/02/2024, 00:01:16Homeconnect BridgeHomeConnectAdding new accessory 'TopRight Steam'
28/02/2024, 00:01:16Homeconnect BridgeHomeConnectStarting events stream for all appliances
...

**Comment by thoukydides** [comment] 2024-02-28 05:52
Duplicate of #195 and #239.

**Closed by thoukydides** 2024-02-28 05:52 UTC
Labels: duplicate
