### ISSUE TITLE
Washing Machine remaining time

### ISSUE THREAD

**Issue by Thijsjuh92** [thoukydides/homebridge-homeconnect#114] opened 2022-12-05 16:07 UTC
#### Description of Enhancement
Please add support to see what the remaining time would be of the  active washing program.
I see the remaining time in the HB logs.. unfortunately not seen in a switch or in the active program switch.

#### HomeKit Mapping

![image](https://user-images.githubusercontent.com/34923899/205685240-4ea11e89-a970-479f-9760-b89d78be4751.jpeg)

#### Home Connect Appliance(s)
Bosch Washing Machine MAWH2643NL-68A40E31678E

**Comment by thoukydides** [comment] 2022-12-05 16:23
Duplicate of #48 

The Remaining Duration is already provided to HomeKit, and displayed in some third-Party (non-Apple) HomeKit apps. However, Apple’s Home app only shows the Remaining Duration for Irrigation System and Valve accessories, neither of which are suitable for the appliances supported by this plugin.

**Closed by thoukydides** 2022-12-05 16:23 UTC
Labels: enhancement, wontfix

**Comment by Thijsjuh92** [comment] 2022-12-05 21:23
@thoukydides Thank you for your reply and unfortunately to hear you won't implement in your plugin.
Great work though.

For now I have added this `valve` characteristic by my self in the `has_remainingtime.js`

Hopefully will add Apple soon new characteristics for Homekit and are you satisfied for implementation:-)
